/-
Copyright (c) 2026 Eric Vergo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Eric Vergo, Claude Fable 5 (Claude Code)
-/
/-
Hopf problem blueprint — logarithmic transforms chapter.

Section 5 of the paper: the two Kodaira logarithmic transforms that fill the elliptic
points of the base, their bielliptic multiple fibres, and the fundamental-group and
homology data those fibres contribute to the topology of X.
-/

import Verso
import VersoManual
import VersoBlueprint
import Macros
import Bibliography
import Solution

open Verso.Genre
open Verso.Genre.Manual hiding citep citet citehere
open Informal

set_option doc.verso true
set_option verso.blueprint.trimTeXLabelPrefix true
set_option pp.rawOnError true

#doc (Manual) "The logarithmic transforms at the elliptic points" =>

The local monodromy of the modular family has finite order at the two elliptic points
$`p_1, p_2` of the $`(3,4,\infty)` base — order $`m_1 = 3` at $`p_1` and $`m_2 = 4` at
$`p_2` — so over a small disc around $`p_j` the family is pulled back from an
$`m_j`-fold cover, and the puncture can be filled canonically. Kodaira's logarithmic
transform {citep kodaira64}[] divides the family over the covering disc by the free
$`\Z/m_j`-action generated by rotating the disc through $`\zeta_j = e^{-2\pi i/m_j}`
while moving the torus fibres by an affine map: in flat coordinates
$$`(z, x) \longmapsto (g_j z,\; A_j x + v/m_j),`
where $`A_j \in \mathrm{GL}_4(\Z)` is the integral monodromy at $`p_j` and $`v` is a
lattice vector fixed by it. The quotient $`N_j` fibres properly over the disc $`D_j`
downstairs, and its fibre over $`p_j` is a multiple fibre $`m_j S_j` whose reduction
$`S_j` is a bielliptic surface {citep alpoge.s6}[].

Whether that action is free is an arithmetic question rather than a geometric one. The
$`m_j`-th power of the generator is translation by $`v \in \Z^4`, hence the identity
on the torus; intermediate powers can fix a point only over the centre of the disc,
where the base rotation is not free; and there they fix a point exactly when every
$`A_j`-invariant integral functional takes an integer value on the fractional
translation $`v/m_j`. With the invariant functionals $`\gamma` and $`\psi_j` this
collapses to one congruence on $`\gamma(v) = v_0`: $`3 \nmid \gamma(v)` for
$`j = 1`, and $`\gamma(v)` odd for $`j = 2`. The threefold is built from
$`v_1 = \varepsilon` and $`v_2 = -\varepsilon'`, for which $`\gamma(v_1) = 1` and
$`\gamma(v_2) = -1`; the pair $`(\ell_1, \ell_2) = (1, -1)` is two thirds of the
discrete gluing data that eventually forces $`\pi_1(X) = 1`.

Two choices shape the formalization. The whole surgery is carried out in flat real
coordinates on $`T^4 = \R^4/\Z^4`, with the complex structure supplied by a period
lattice and transported back and forth by the period isomorphism, so that every
order and fixed-point computation is an assertion about integer matrices that
`decide` can settle. And the transform is realised as a *gauge equivalence* rather
than a cut-and-paste: translating the fibres by the multivalued section
$`\tfrac{\log z}{2\pi i}\,\omega_v(z)` conjugates the twisted action into the untwisted
one, so the punctured filling is biholomorphic to the piece of the original family it
replaces, and no gluing of charts by hand is ever needed. What this chapter produces is
consumed twice downstream: the manifold structure and the punctured-filling
biholomorphism are what allow $`N_1` and $`N_2` to be glued into $`X`, while the
deformation retraction onto $`S_j`, the deck-group description of $`\pi_1(S_j)`, the
meridian identification, and the integral homology of $`S_j` are the local input to
the van Kampen and Mayer–Vietoris computations.

:::group "elliptic"
The flat model of the twist, the arithmetic condition that makes it free, the fillings
$`N_1, N_2` as complex threefolds, and the gauge transformation that identifies each
punctured filling with the family it replaces.
:::

:::definition "def:elliptic-kind" (lean := "Mathoverflow1973.Elliptic.Kind") (parent := "elliptic") (uses := "def:a, def:lattice")
*Definition.* The two elliptic points are indexed by a two-element type with
constructors `three` and `four`, carrying decidable equality and a `Fintype` instance.
Each kind $`j` determines its order `Kind.order` — $`3` and $`4` — its integral
monodromy matrix `Kind.matrix`, namely $`A_1` and $`A_2`, and a distinguished twist
vector `Kind.twist`, namely $`\varepsilon = (1,2,-4,0)` and
$`-\varepsilon' = -(1,3,-3,0)`. The two facts the rest of the construction rests on are
verified by `decide` on the two cases: $`A_j^{m_j} = 1` (`Kind.matrix_pow_order`) and
$`A_j v_j = v_j` (`Kind.matrix_fixes_twist`). This is the most referenced declaration
of the subject module: the index $`j \in \{1,2\}` of the paper's §5 is a value of this
type throughout, and everything about the elliptic fillings is stated uniformly in it.
:::

Writing the twist as a fraction of a lattice vector is what makes the flat picture
useful. On the universal cover $`\R^4` of the fibre torus the generator of the surgery
group is an honest affine map, its linear part integral and its translation part
rational with denominator $`m_j`, and the whole of the paper's Proposition 5.6 becomes
a statement about iterating that map modulo $`\Z^4`.

:::definition "def:elliptic-flat-affine" (lean := "Mathoverflow1973.Elliptic.flatAffine") (parent := "elliptic") (uses := "def:elliptic-kind, def:lattice")
*Definition.* For a kind $`j` and a lattice vector $`v \in \Z^4`, the affine self-map
of $`\R^4` given by
$$`x \longmapsto A_j x + \tfrac{1}{m_j} v .`
The linear part is `flatLinear j`, the multiplication map of $`A_j` after the
entrywise cast $`\Z \to \R`, and the translation part is $`\tfrac{1}{m_j}` times the
cast `realCast v` of $`v`. Descended to $`T^4 = \R^4/\Z^4` this generates the
$`\Z/m_j`-twist of the logarithmic transform. The companion relation `FlatCongruent`,
$`x - y \in \Z^4`, is equality after descent, and is the form in which fixed points of
the descended map are quantified.
:::

:::definition "def:admissible-twist" (lean := "Mathoverflow1973.Elliptic.AdmissibleTwist") (parent := "elliptic") (uses := "def:elliptic-kind, def:lattice")
*Definition.* A lattice vector $`v` is an admissible twist for the kind $`j` when
$`A_j v = v` and, in addition, $`3 \nmid \gamma(v)` if $`j` is the kind of order
three, while $`\gamma(v)` is odd if $`j` is the kind of order four; here
$`\gamma(v) = v_0` is the first coordinate functional. The Lean statement is a
conjunction whose second component is a `if j = .three then _ else _` branch on the
decidable equality of kinds, so the two congruences of the paper are carried by a
single predicate. Admissibility is exactly what makes the twisted $`\Z/m_j`-action
free, and every construction of the chapter takes it as a hypothesis.
:::

:::theorem "thm:main-twist-admissible" (lean := "Mathoverflow1973.Elliptic.mainTwist_admissible") (parent := "elliptic") (uses := "def:admissible-twist")
*Theorem.* The distinguished twist of each kind is admissible: `AdmissibleTwist j j.twist`
holds for both $`j`.
:::

:::proof "thm:main-twist-admissible"
The first component is `Kind.matrix_fixes_twist`. For the second, $`\gamma` reads off
the first coordinate: $`\gamma(\varepsilon) = 1`, which is not divisible by $`3`, and
$`\gamma(-\varepsilon') = -1`, which is odd. Both are decided by unfolding the twist
vectors. $`\blacksquare`
:::

:::theorem "thm:flat-affine-free-iff" (lean := "Mathoverflow1973.Elliptic.flatAffine_free_iff") (parent := "elliptic") (uses := "def:a, def:admissible-twist, def:elliptic-flat-affine")
*Theorem.* Let $`v` satisfy $`A_j v = v`. Then no proper iterate of the affine map
$`x \mapsto A_j x + \tfrac{1}{m_j}v` fixes a point modulo $`\Z^4` — that is,
$`(\mathrm{flatAffine}_j^{\,v})^{r}(x) \not\equiv x` for all $`x \in \R^4` and all
$`0 < r < m_j` — if and only if $`v` is an admissible twist. This is the exact freeness
criterion: the sufficiency is what the construction needs, and the necessity, proved
here as well, says the two congruences cannot be weakened.
:::

:::proof "thm:flat-affine-free-iff"
Sufficiency is `flatAffine_iterate_not_congruent`: the $`r`-th iterate is
$`x \mapsto A_j^r x + \tfrac{r}{m_j}v`, and a congruence
$`A_j^r x + \tfrac{r}{m_j}v \equiv x` forces every $`A_j^r`-invariant integral
functional to take an integer value on $`\tfrac{r}{m_j}v`, which the congruence on
$`\gamma(v)` forbids for $`0 < r < m_j`. For necessity the failing iterate is exhibited
concretely. If $`3 \mid \gamma(v)` in the order-three case,
`bad_three_twist_has_fixed_point` writes down a point of $`\R^4` fixed already by the
first iterate; if $`\gamma(v)` is even in the order-four case,
`bad_four_twist_has_square_fixed_point` writes down a point fixed by the *second*
iterate — the failure there is genuinely at $`r = 2`, not at $`r = 1`. Both witnesses
are explicit rational vectors, and the verification is a coordinatewise computation
with the entries of $`A_1` and $`A_2`. $`\blacksquare`
:::

The flat torus carries no complex structure of its own. It acquires one from a period
lattice, and for the filling to close up over the centre of the disc the period has to
be a fixed point of the elliptic modular step, so that the twist is a biholomorphism
rather than merely a diffeomorphism.

:::definition "def:fixed-period" (lean := "Mathoverflow1973.Elliptic.FixedPeriod") (parent := "elliptic") (uses := "def:elliptic-kind, def:period-domain")
*Definition.* The subtype of period domains fixed by the elliptic step of the kind
$`j`: those $`p` with $`\mathrm{step}_1(p) = p` for the kind of order three and
$`\mathrm{step}_2(p) = p` for the kind of order four. These are the complex-multiplication
periods sitting over the elliptic fixed points, and the associated complex $`2`-torus is
the paper's central fibre $`A_0^{(j)} = \C^2/L(z_j)`. The type is inhabited for both
kinds by `examplePeriod`, built from the explicit period points with
$`\tau = (1 + i\sqrt{3})/2` and $`\tau = i` respectively, whose admissibility and
fixedness are checked directly.
:::

:::definition "def:flat-torus-affine" (lean := "Mathoverflow1973.Elliptic.flatTorusAffine") (parent := "elliptic") (uses := "def:elliptic-kind, def:fixed-period, def:lattice, def:period-domain")
*Definition.* The self-homeomorphism of $`T^4 = \R^4/\Z^4` of order $`m_j` induced by
$`x \mapsto A_j x + \tfrac{1}{m_j}v`. It is not defined by descent but by transport:
the biholomorphism `affineBiholomorph` of the complex $`2`-torus of the fixed period
`exampleFixedPeriod j` is conjugated through `flatTorusPeriodHomeomorph`, the
identification of the flat torus with the period torus supplied by the period basis.
The simp lemma `flatTorusAffine_mkQ` recovers the flat description,
$`[x] \mapsto [A_j x + \tfrac{1}{m_j}v]`. Building it this way is what makes the same
map simultaneously a homeomorphism of $`T^4` and, in period coordinates, a
biholomorphism of a complex torus — the content of the paper's flat trivialisation
$`\Xi`.
:::

:::definition "def:elliptic-surface" (lean := "Mathoverflow1973.Elliptic.Surface") (parent := "elliptic") (uses := "def:a, def:admissible-twist, def:elliptic-flat-affine, def:fixed-period, def:period-domain")
*Definition.* The bielliptic surface attached to a fixed period $`p` and an admissible
twist $`v`: the quotient of the complex $`2`-torus of $`p` by the $`\Z/m_j`-action
generated by the affine biholomorphism $`x \mapsto A_j x + \tfrac{1}{m_j}v`. Freeness
of that action is `affineAction_free`, which is the previous criterion read through
the period identification; the quotient is formed by the chapter's `FiniteQuotient`
theory for free actions of finite groups on locally compact Hausdorff spaces. The
surface is compact and path connected, and `surfaceProjection` is an $`m_j`-sheeted
covering by the torus (`surfaceProjection_fibre_card`). This is the paper's
$`S_j = A_0^{(j)}/\langle x \mapsto A_j x + v/m_j\rangle`, the reduction of the multiple
fibre.
:::

:::definition "def:elliptic-filling" (lean := "Mathoverflow1973.Elliptic.Filling") (parent := "elliptic") (uses := "def:a, def:admissible-twist, def:elliptic-flat-affine, def:flat-torus-affine, def:holomorphic-period-map")
*Definition.* The local model of the logarithmic transform: the quotient of the total
space of the holomorphic family of complex $`2`-tori over the unit disc — as a type
$`\Delta \times T^4`, with the analytic structure coming from the special period map of
the kind $`j` — by the $`\Z/m_j`-action generated by `familyPermutation`, the product
of the disc rotation `familyRotation` through a primitive $`m_j`-th root of unity with
the affine torus twist `flatTorusAffine`. The quotient inherits a `ChartedSpace`
structure on the model $`\C \times \C^2` and the quotient map is an $`m_j`-sheeted
holomorphic covering (`fillingQuotient_isCoveringMap`, `fillingQuotient_holomorphic`).
This is the paper's $`N_j = J_j'/\langle \tilde g_j^{\log}\rangle`.
:::

:::definition "def:filling-projection" (lean := "Mathoverflow1973.Elliptic.fillingProjection") (parent := "elliptic") (uses := "def:elliptic-filling")
*Definition.* The map $`N_j \to \Delta` obtained by descending $`(z, x) \mapsto z^{m_j}`
along the quotient; the descent is legitimate because the disc rotation raised to the
$`m_j`-th power is the identity, so `upstairsProjection` is invariant under the action.
Downstairs this is the paper's $`f_j \colon N_j \to D_j` in the coordinate
$`t_j = s_j^{m_j}`, and the multiple fibre sits over $`0`.
:::

:::theorem "thm:filling-projection-fibre-connected" (lean := "Mathoverflow1973.Elliptic.fillingProjection_fibre_connected") (parent := "elliptic") (uses := "def:filling-projection")
*Theorem.* Every fibre of $`N_j \to \Delta` is connected.
:::

:::proof "thm:filling-projection-fibre-connected"
Choose an $`m_j`-th root $`z` of the base point, which exists because
$`z \mapsto z^{m_j}` is surjective on the disc. The fibre is then exactly the image of
the single torus fibre over $`z` under `torusFibreMap`, a continuous image of a
connected space. Over a nonzero base point the $`m_j` distinct torus fibres above it
are identified with one another by the action, so the fibre is a single torus; over
$`0` the $`m_j` roots coincide, the action moves the one fibre by the affine twist, and
the image is the bielliptic surface — the reduction of the multiple fibre $`m_j S_j`.
$`\blacksquare`
:::

Everything so far is stated for the concrete family over the disc. The construction is
then repeated verbatim for an abstract period map with the right equivariance, and it
is that abstract version the threefold chapter instantiates — twice, once at each
elliptic point, from the global period map restricted near $`p_j`.

:::definition "def:equivariant-data" (lean := "Mathoverflow1973.Elliptic.Equivariant.Data") (parent := "elliptic") (uses := "def:elliptic-kind, def:holomorphic-period-map")
*Definition.* A structure carrying a holomorphic period map over the unit disc together
with one axiom, the covariance
$$`\mathrm{point}(\mathrm{rotation}_j\, z) = \mathrm{step}_j(\mathrm{point}\, z)`
for every $`z`: rotating the disc through $`\zeta_j` moves the period point by the
elliptic modular step. That single hypothesis is enough to rebuild the whole filling —
the free $`\Z/m_j`-action, the quotient `Data.Space`, its charts, its projection to the
disc and its central fibre. `SpecialPeriods.EllipticFilling.localData` and
`specialLocalData` supply the instances from the global period map near $`p_1` and
$`p_2`, and the actual pieces of the threefold are `SpecialFullFilling j`.
:::

:::theorem "thm:data-is-manifold-2" (lean := "Mathoverflow1973.Elliptic.Equivariant.Data.isManifold") (parent := "elliptic") (uses := "def:admissible-twist, def:equivariant-data, thm:covering-quotient-is-manifold")
*Theorem.* For an admissible twist, the quotient `D.Space v hv` is an analytic complex
manifold modelled on $`\C \times \C^2` — that is, each $`N_j` is a complex threefold.
:::

:::proof "thm:data-is-manifold-2"
The quotient map is a covering map because the action is free, continuous and by a
finite group, and it is holomorphic because both factors of the generator are
(`action_holomorphic`); `CoveringQuotient.isManifold` then transports the analytic
structure of the total space through the covering. The smoothness index is $`\omega`,
not $`\infty` or $`1`: the charts obtained downstairs are analytically compatible,
which is stronger than the atlas the final theorem needs. Two encoding points are worth
noting. The `ChartedSpace` structure on the quotient is never a global instance — it is
threaded through `letI` and `attribute [local instance]`, because the quotient type
depends on the action and unification cannot be trusted to find it. And each fibre of
the covering has exactly $`m_j` points (`quotient_fibre_card`), which is the sense in
which the fibre over the centre appears with multiplicity $`m_j`. $`\blacksquare`
:::

The transform is invisible away from the multiple fibre, and the way the formalization
shows this is by exhibiting the identification rather than by cutting and pasting.
Translating each torus fibre by a logarithmic section turns the twisted action into the
untwisted one; the induced map on quotients is then the gluing interface.

:::definition "def:log-gauge-gauge-map" (lean := "Mathoverflow1973.Elliptic.LogGauge.gaugeMap") (parent := "elliptic") (uses := "def:holomorphic-period-map, def:lattice")
*Definition.* On the part of the family lying over the punctured disc, the map that
translates the fibre over $`z` by the section coordinate
$$`\Pi(z)^{-1}\left(\frac{\log z}{2\pi i}\,\omega_v(z)\right) \bmod \Z^4,`
where $`\omega_v(z) = \Pi(z)v` is the period vector of the twist $`v` and $`\Pi(z)` is
the period isomorphism $`\R^4 \to \C^2`. The logarithm is multivalued, but changing its
branch changes the argument by an integer, and an integer multiple of $`\omega_v(z)` is
a lattice period; the translation is therefore well defined on the fibre
(`quotientMap_integer_period`). Conjugation by this map carries the $`v`-twisted
$`\Z/m_j`-action to the untwisted one (`gaugeMap_intertwines`), and the map is
holomorphic (`gaugeMap_holomorphic`). It is the paper's fibrewise translation $`h_j`
by $`\sigma_j(z) = \tfrac{\log s_j(z)}{2\pi i}\Pi(z)v`.
:::

:::definition "def:main-filling-to-tautological-biholomorph" (lean := "Mathoverflow1973.Elliptic.LogGauge.mainFillingToTautologicalBiholomorph") (parent := "elliptic") (uses := "def:cusp-uniformization-exponential, def:equivariant-data, def:log-gauge-gauge-map, thm:covering-quotient-is-manifold, thm:main-twist-admissible")
*Definition.* An analytic diffeomorphism, for the distinguished twist $`j.\mathrm{twist}`,
from the punctured filling — the open subset of $`N_j` lying over the punctured disc —
to the tautological quotient, the same construction carried out with twist $`0`. It is
obtained from the gauge map by passing to quotients and comparing the two open
quotients, and `mainFillingToTautologicalBiholomorph_base` records that it commutes
with the projections to the punctured disc. This is the paper's
$`G_j \colon N_j \setminus S_j \xrightarrow{\ \sim\ } J|_{D_j^*}`: away from the
multiple fibre the logarithmic transform changes nothing, and this map is the collar
along which $`N_j` is glued into $`X`.
:::

:::group "elliptic-topology"
The homotopy-theoretic output of the fillings: the bielliptic fibre as a mapping torus,
its fundamental group as an affine crystallographic group, the meridian of the multiple
fibre, and the integral homology that enters the Mayer–Vietoris computation.
:::

Everything the topology of $`X` needs about $`N_j` is really about $`S_j`, because the
filling retracts onto its central surface. The surface in turn is computed by splitting
the flat torus so that the twist direction becomes a circle factor: the quotient then
becomes a mapping torus of a diffeomorphism of $`T^3`, and the Wang sequence
{citep hatcher02}[] reduces its homology to kernels and cokernels of $`1 - A` on the
exterior powers of $`\Z^3`.

:::definition "def:fibre-matrix" (lean := "Mathoverflow1973.Elliptic.HigherHomology.fibreMatrix") (parent := "elliptic-topology") (uses := "def:elliptic-kind")
*Definition.* The explicit integer matrices of the two kinds, of order three and of
order four respectively:
$$`\begin{pmatrix} 0 & 1 & 0 \\ -1 & -1 & 0 \\ 1 & 0 & 1 \end{pmatrix} \quad\text{and}\quad \begin{pmatrix} 0 & -1 & 0 \\ 1 & 0 & 0 \\ 0 & 1 & 1 \end{pmatrix}`
Both have determinant $`1` and order $`m_j`, verified by `decide`, so each defines an
element `fibreSL j` of $`\mathrm{SL}_3(\Z)` and hence a diffeomorphism of $`T^3` of
order $`m_j`. This is the monodromy of the
$`T^3`-fibre once the twist direction has been split off as a circle;
`fibreSquareMatrix` is its second exterior power, also written out explicitly, and the
two together carry every homology computation of this group.
:::

:::definition "def:surface-mapping-torus-homeomorph" (lean := "Mathoverflow1973.Elliptic.HigherHomology.surfaceMappingTorusHomeomorph") (parent := "elliptic-topology") (uses := "def:elliptic-surface, def:fibre-matrix, def:flat-torus-affine, def:mapping-torus-torus, def:torus-matrix-map, thm:main-twist-admissible")
*Definition.* A homeomorphism from the bielliptic surface with the distinguished twist
to the mapping torus of the order-$`m_j` diffeomorphism of $`T^3` determined by
`fibreMatrix j`. It factors as the change of basis `splitFlatTorusHomeomorph`, an
explicit element of $`\mathrm{GL}_4(\Z)` (`twistBasisMatrix`) chosen so that the twist
direction becomes the circle factor of $`T^4 \cong S^1 \times T^3` and the affine map
becomes rotation by $`1/m_j` on the circle times the `fibreMatrix` action on $`T^3`,
followed by the identification of the resulting $`\Z/m_j`-quotient with a mapping torus.
Every statement about the homology of $`S_j` is proved through this presentation.
:::

:::definition "def:filling-surface-strong-deformation-retraction" (lean := "Mathoverflow1973.Elliptic.Equivariant.Data.fillingSurfaceStrongDeformationRetraction") (parent := "elliptic-topology") (uses := "def:admissible-twist, def:equivariant-data")
*Definition.* A homotopy from the identity of $`N_j` to the composite of the retraction
onto the central surface with its inclusion, stationary on the surface throughout — a
strong deformation retraction, expressed in Lean as a `HomotopyRel` relative to the
range of `surfaceIntoFilling`. The homotopy is the radial contraction `fillingRadial`
of the disc coordinate, which descends to the quotient because scaling commutes with
rotation. Consequently $`N_j \simeq S_j`, and every homotopy invariant of the piece —
its fundamental group, its homology — may be read off the bielliptic surface.
:::

:::theorem "thm:coinvariant-map-ker-eq-range" (lean := "Mathoverflow1973.Elliptic.coinvariantMap_ker_eq_range") (parent := "elliptic-topology") (uses := "def:a, def:elliptic-kind, def:lattice")
*Theorem.* The kernel of the map $`\Z^4 \to \Z^2`, $`w \mapsto (\gamma(w), \psi_j(w))`,
is exactly the image of $`A_j - 1`, where $`\psi_1(w) = 2w_1 + w_2 + 3w_3` and
$`\psi_2(w) = w_1 + w_2 + 2w_3`. Since the map is also surjective, the coinvariant
lattice $`\Z^4/(A_j - 1)\Z^4` is free of rank $`2` with $`(\gamma, \psi_j)` as
coordinates — the computation behind $`H_1(S_j;\Z) \cong \Z^2` and its torsion
freeness. The functionals are the ones the paper produces as a basis of the space fixed
by the transpose monodromy; both inclusions are checked coordinatewise against the
entries of $`A_1` and $`A_2`, with the lifting map `coinvariantKernelLift` supplying
the preimage in the harder direction.
:::

:::theorem "thm:deck-generator-pow-order" (lean := "Mathoverflow1973.Elliptic.deckGenerator_pow_order") (parent := "elliptic-topology") (uses := "def:elliptic-flat-affine, def:elliptic-kind, def:lattice")
*Theorem.* In the group of affine automorphisms of $`\R^4` generated by the integer
translations and by $`g \colon x \mapsto A_j x + \tfrac{1}{m_j}v`, the relation
$$`g^{\,m_j} = t_v`
holds whenever $`A_j v = v`: the $`m_j`-th power of the generator is translation by the
twist vector. This is the defining relation of the crystallographic group
$`1 \to \Z^4 \to \Gamma \to \Z/m_j \to 1` presenting $`\pi_1(S_j)`, and it is the
source of the multiplicities $`3` and $`4` in the van Kampen presentation of
$`\pi_1(X)`: a meridian of the multiple fibre becomes trivial only after $`m_j` turns,
up to a loop in the fibre.
:::

:::definition "def:surface-fundamental-group-deck-equiv" (lean := "Mathoverflow1973.Elliptic.surfaceFundamentalGroupDeckEquiv") (parent := "elliptic-topology") (uses := "def:elliptic-surface, thm:covering-comp-of-finite-fibres, thm:flat-affine-free-iff")
*Definition.* For each point $`y \in \R^4`, an isomorphism of groups
$$`\pi_1\big(S_j,\, [y]\big) \;\cong\; \Gamma_{j,v}`
onto the affine deck group generated by $`\Z^4`-translations and
$`g \colon x \mapsto A_j x + \tfrac{1}{m_j}v`. The universal covering is the composite
$`\R^4 \to T^4 \to S_j`, a covering map because a composite of coverings with finite
fibres is one, and `affineCoverProjection_isQuotientCoveringMap` identifies its fibres
with the deck-group orbits — which is where freeness of the twisted action is used. The
covering-space theory then yields an anti-isomorphism onto the deck group, and this
declaration composes it with inversion to obtain an isomorphism; the sign convention is
what makes the meridian statement below land on an inverse.
:::

:::definition "def:surface-homology-coordinates" (lean := "Mathoverflow1973.Elliptic.HigherHomology.surfaceHomologyCoordinates") (parent := "elliptic-topology") (uses := "def:fibre-matrix, def:flat-torus-circle-homeomorph, def:mapping-torus-homology-wang-boundary, def:period-torus-higher-homology-pontryagin-product, def:product-torus-top-class, def:surface-mapping-torus-homeomorph, thm:intersection-to-v-twisted-fold, thm:singular-mayer-vietoris-exact-at-pair")
*Definition.* For every degree $`n`, an isomorphism of $`\Z`-modules
$$`H_n\big(S_j;\Z\big) \;\cong\; \Z^{\,b_n}, \qquad b = (1,2,2,2,1),`
with $`b_n = 0` for $`n \ge 5` — the complete integral homology of the reduced multiple
fibre, and exactly the Betti numbers of a bielliptic surface. It is the transport of
the mapping-torus presentation along `surfaceMappingTorusHomeomorph` followed by the
degreewise identifications assembled from the Wang sequence, whose connecting map
reduces each degree to the kernel and cokernel of $`1 - A` on
$`\Lambda^k \Z^3`; those are computed with the explicit matrices `fibreMatrix` and
`fibreSquareMatrix`. The homology is the subject module's own singular theory, built
from scratch with a Mayer–Vietoris sequence, and the degreewise statements
`surfaceH0Equiv` through `surfaceH4Equiv` are available separately.
:::

The last two results are the ones the global chapters actually quote. The first says
what a small loop around the multiple fibre does in $`\pi_1` of the reduced fibre; the
second says which classes of the covering torus die in the surface.

:::theorem "thm:surface-fundamental-group-deck-equiv-log-meridian" (lean := "Mathoverflow1973.Elliptic.LogGauge.surfaceFundamentalGroupDeckEquiv_logMeridian") (parent := "elliptic-topology") (uses := "def:cusp-uniformization-exponential, def:equivariant-data, def:flat-torus-affine, def:surface-fundamental-group-deck-equiv, thm:deck-generator-pow-order")
*Theorem.* The meridian loop encircling the multiple fibre, pushed into the central
surface, represents the inverse of the deck generator: its class under the isomorphism
$`\pi_1(S_j) \cong \Gamma_{j,v}` is $`(\mathrm{deckGenerator}\, j\, v)^{-1}`.
:::

:::proof "thm:surface-fundamental-group-deck-equiv-log-meridian"
The loop is built upstairs and pushed down. Fix $`s_0` with $`\operatorname{Im} s_0 > 0`
and let the parameter run along $`s(t) = s_0 - t/m_j`, so that the base point
$`z(t) = e^{2\pi i s(t)}` traverses one $`m_j`-th of a turn of the circle
$`|z| = |e^{2\pi i s_0}|`, and its $`m_j`-th power — the coordinate downstairs — goes
exactly once around the puncture. Over it the fibre coordinate follows the negative
logarithmic section $`-s(t)\,\omega_v(z(t))` in flat coordinates. At $`t = 1` the flat
point is the image of the flat point at $`t = 0` under the affine generator
$`x \mapsto A_j x + \tfrac{1}{m_j}v` (`logMeridianFlat_one`), so upstairs the path
joins a point to its image under the generator, and downstairs it closes into a loop
(`logMeridianLoop`). Retracting along the deformation retraction of the filling carries
that loop into the central surface without changing its class. A path from a point to
its image under the generator represents, under the covering-space isomorphism, the
generator itself up to the anti-isomorphism convention; composing with the inversion
built into `surfaceFundamentalGroupDeckEquiv` gives the inverse. Combined with
$`g^{m_j} = t_v`, this is precisely the local relation that van Kampen turns into the
multiplicities $`3` and $`4` in $`\pi_1(X)`. $`\blacksquare`
:::

:::theorem "thm:period-cover-h1-ker-eq-deck-difference-range" (lean := "Mathoverflow1973.Elliptic.HigherHomology.periodCover_h1_ker_eq_deckDifference_range") (parent := "elliptic-topology") (uses := "def:circle-product-homology-equiv, def:flat-torus-circle-homeomorph, def:homeomorph-homology-equiv, def:surface-mapping-torus-homeomorph, thm:singular-mayer-vietoris-exact-at-pair, thm:wang-boundary-product-cover")
*Theorem.* For the $`m_j`-sheeted covering of the bielliptic surface by the period
torus, the kernel of the induced map on first homology is exactly the image of
$`1 - \sigma_*`, where $`\sigma` is the deck monodromy:
$$`\ker\big(H_1(T_p;\Z) \to H_1(S_j;\Z)\big) \;=\; \operatorname{im}\big(1 - \sigma_*\big).`
The same statement is proved in every degree $`0 \le n \le 4`.
:::

:::proof "thm:period-cover-h1-ker-eq-deck-difference-range"
One inclusion is formal: $`\sigma` acts trivially after projecting to the quotient, so
the image of $`1 - \sigma_*` lies in the kernel. For the reverse inclusion the induced
map is factored through the coinvariants, giving
$`H_n(T_p)/\operatorname{im}(1 - \sigma_*) \to H_n(S_j)`, and the claim becomes the
injectivity of that map. Injectivity is verified by computing both sides in the
mapping-torus coordinates: the coinvariants are identified with $`\Z^2` through the
cokernels supplied by the Wang sequence, the target through the homology coordinates of
the surface, and the induced map between them becomes an explicit integer matrix whose
injectivity is decided. The degrees $`n = 0, 2, 3, 4` are treated identically, each
with its own coinvariant identification. This is the form the elliptic pieces enter the
Mayer–Vietoris computation of $`H_*(X)`: it says exactly which cycles of the general
fibre survive into the multiple fibre. $`\blacksquare`
:::
