/-
Copyright (c) 2026 Eric Vergo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Eric Vergo, Claude Fable 5 (Claude Code)
-/
/-
Hopf problem blueprint — Uniformizing the (3,4,∞) orbifold chapter.

The base of Alpöge's fibred threefold: the (3,4,∞) triangle group acting on the upper
half-plane, its orbit space compactified to a Riemann surface biholomorphic to P¹, and
the three period functions τ, μ, β assembled into the period map of Theorem 3.4.
-/

import Verso
import VersoManual
import VersoBlueprint
import Macros
import Bibliography
import Solution

open Verso.Genre
open Verso.Genre.Manual hiding citep citet citehere
open Informal

set_option doc.verso true
set_option verso.blueprint.trimTeXLabelPrefix true
set_option pp.rawOnError true

#doc (Manual) "Uniformizing the (3,4,∞) orbifold" =>

The threefold of {citet alpoge.s6}[] is fibred over a base curve, and that curve is not
bare: it is the projective line carrying orbifold structure, with cone points of orders
$`3` and $`4` at $`t = 0` and $`t = 1` and a puncture at $`t = \infty`. Uniformizing it
replaces the orbifold $`(\PP^1; 3, 4, \infty)` by a discrete group acting on the upper
half-plane — the $`(3,4,\infty)` triangle group $`\Gamma \cong \Z/3 * \Z/4`, generated
by an elliptic element $`g_1` of order $`3`, an elliptic $`g_2` of order $`4`, and their
inverse product $`g_0 = (g_1g_2)^{-1}`, which is parabolic. Every object downstream —
the two-torus fibres, their monodromy, the toric filling at the cusp, the fundamental
group computation — is written on $`\mathbb{H}` and descends through $`\Gamma`.

Two things then have to be proved, and neither is available off the shelf. First, that
the quotient really is a compact Riemann surface isomorphic to $`\PP^1`: the group must
be shown discrete and its action properly discontinuous, the orbit space charted at the
two cone points and at the cusp, and the resulting surface uniformized. Second — and
this is the analytic heart of the paper's §3 — that there exist three holomorphic
functions $`\tau, \mu, \beta` on $`\mathbb{H}`, equivariant for $`\Gamma` in a precise
layered sense: $`\tau` transforms by Möbius steps, $`\mu` by an affine cocycle over
$`\tau`, $`\beta` by an additive cocycle over $`(\tau,\mu)`. Their values assemble the
period matrix of the torus fibres, and their transformation laws are the monodromy.

The formalization takes the long route on both counts. Discreteness is established by
exhibiting an explicit identity-test neighbourhood in $`SL(2,\R)` rather than invoking
any general theory of Fuchsian groups; the classical Shimizu–Leutbecher inequality is
proved from scratch by commutator iteration; the modular $`j`-function and its mapping
properties are developed on top of Mathlib's Eisenstein series; and the sheaf-cohomology
arguments of the paper — $`H^0` and $`H^1` of $`\mathcal{O}_{\PP^1}(-1)` vanish, so the
$`\mu`-torsor has a unique section; $`H^1(\PP^1,\mathcal{O}) = 0`, so the
$`\beta`-torsor has one — are replaced by hands-on patching of local equivariant
sections over a cusp/elliptic/regular cover, with a rigidity argument in place of the
vanishing of global sections.

# The group and its quotient

:::group "orbifold"
The $`(3,4,\infty)` triangle group as a free product, its faithful and properly
discontinuous action on the upper half-plane by Möbius transformations, and the
compactified orbit space with its structure of a Riemann surface biholomorphic to the
projective line.
:::

The construction starts from two explicit matrices and one real constant. The constant
is not a choice: it is what makes the two elliptic generators close up into a discrete
group with a cusp.

:::definition "def:triangle-width" (lean := "Mathoverflow1973.SpecialPeriods.Triangle.width") (parent := "orbifold")
The cusp width is the real number $`w = 1 + \sqrt2`. It satisfies $`w^2 = 2w + 1`,
equivalently $`(w-1)^2 = 2`, and this identity is what every closed-form computation in
the group ultimately reduces to. Three roles: $`w` is the translation length of the
parabolic cusp generator, so the cusp stabiliser is generated by $`z \mapsto z - w`; it
is the period of the local parameter $`q = e^{2\pi i z/w}` at the cusp; and it is the
width of the vertical strip cut out by the Ford fundamental domain, whose bounding lines
are $`\operatorname{Re} z = -(w+1)/2` and $`\operatorname{Re} z = (w-1)/2`.
:::

:::definition "def:triangle-generator-one-sl" (lean := "Mathoverflow1973.SpecialPeriods.Triangle.generatorOneSL") (parent := "orbifold")
The first generator is
$$`g_1 = \begin{pmatrix} 0 & -1 \\ 1 & 1\end{pmatrix} \in SL(2,\R).`
It satisfies $`g_1^3 = -I` and fixes the point
$`\rho - 1 = -\tfrac12 + \tfrac{\sqrt3}{2}i` of the upper half-plane, where
$`\rho = e^{i\pi/3}`. The development works throughout in $`SL(2,\R)` and never forms
the projective quotient: the relation recorded is $`g_1^3 = -I`, and the order-$`3`
statement is transported to the induced permutation of $`\mathbb{H}`, where $`-I` acts
trivially, so that the Möbius transformation of $`g_1` has order exactly $`3`.
:::

:::definition "def:triangle-generator-two-sl" (lean := "Mathoverflow1973.SpecialPeriods.Triangle.generatorTwoSL") (parent := "orbifold") (uses := "def:triangle-width")
The second generator is
$$`g_2 = \begin{pmatrix} 1 & w+1 \\ -1 & -w\end{pmatrix} \in SL(2,\R),`
with $`g_2^4 = -I`, so its Möbius transformation has order exactly $`4`; its fixed point
in the upper half-plane is $`-\tfrac{w+1}{2} + \tfrac{w-1}{2}i`, a corner of the Ford
domain on its left edge. The product is the horizontal translation
$$`g_1 g_2 = \begin{pmatrix} 1 & w \\ 0 & 1\end{pmatrix},`
so the cusp generator $`g_0 = (g_1g_2)^{-1}` acts by $`z \mapsto z - w`. The sign is the
one the paper has to argue for separately (Remark 2.12): here it is visible in the
matrix.
:::

:::definition "def:special-periods-triangle-group" (lean := "Mathoverflow1973.SpecialPeriods.TriangleGroup") (parent := "orbifold")
The triangle group is defined abstractly, as the free product $`\Z/3 * \Z/4` — in Lean
`Monoid.Coprod (Multiplicative (ZMod 3)) (Multiplicative (ZMod 4))`, the two cyclic
groups written multiplicatively. Its distinguished generators are the images of $`1`
under the two injections; their orders are exactly $`3` and $`4`, and the cusp generator
is $`g_0 = (g_1g_2)^{-1}`, so that $`g_1 g_2 g_0 = 1`. Defining the group by a
presentation rather than as a subgroup of $`PSL(2,\R)` is what makes the rest of the
chapter modular: the universal property `triangleLift` says a homomorphism out of
$`\Gamma` is nothing but a pair of elements of orders dividing $`3` and $`4`, and the
same group is then made to act on $`\mathbb{H}`, on $`SL(4,\Z)`, and on the real
four-torus, with the three actions compatible by construction.
:::

:::definition "def:triangle-geometric-representation" (lean := "Mathoverflow1973.SpecialPeriods.triangleGeometricRepresentation") (parent := "orbifold") (uses := "def:special-periods-triangle-group, def:triangle-generator-one-sl, def:triangle-generator-two-sl")
The geometric action is the homomorphism $`\Gamma \to \operatorname{Perm}(\mathbb{H})`
sending $`g_1` and $`g_2` to the Möbius transformations of the two matrices, obtained
from the universal property using $`g_1^3 = g_2^4 = 1` in
$`\operatorname{Perm}(\mathbb{H})`. The target is the full permutation group of the
half-plane rather than a group of matrices, so the resulting `MulAction` is by
bijections of $`\mathbb{H}`; that each acting bijection is in fact a biholomorphism is a
separate theorem. The cusp generator acts by the translation $`z \mapsto z - w`.
:::

:::definition "def:triangle-ford-region" (lean := "Mathoverflow1973.SpecialPeriods.Triangle.fordRegion") (parent := "orbifold") (uses := "def:triangle-width")
The Ford fundamental domain is
$$`\mathcal{F} = \Big\{ z \in \mathbb{H} : -\tfrac{w+1}{2} \le \operatorname{Re} z \le \tfrac{w-1}{2},\ |z| \ge 1,\ |z+1| \ge 1 \Big\},`
a closed hyperbolic quadrilateral: a vertical strip of width exactly $`w`, truncated
below by the two unit circles centred at $`0` and $`-1`. Those two circles meet at the
order-$`3` fixed point $`\rho - 1`, and the order-$`4` fixed point is the corner where the
left edge of the strip meets the circle $`|z+1| = 1`. Every $`\Gamma`-orbit meets
$`\mathcal{F}`, so the translates $`\{g\mathcal{F}\}` cover $`\mathbb{H}`, and points of
$`\mathcal{F}` have imaginary part bounded below — the two facts the orbit space is built
on. Local finiteness of the translates is available too, but only downstream of proper
discontinuity, which is extracted from the matrix group instead.
:::

:::theorem "thm:triangle-geometric-representation-injective" (lean := "Mathoverflow1973.SpecialPeriods.triangleGeometricRepresentation_injective") (parent := "orbifold") (uses := "def:triangle-geometric-representation")
*Theorem.* The geometric representation $`\Gamma \to \operatorname{Perm}(\mathbb{H})` is
injective. Equivalently: the group of Möbius transformations generated by $`g_1` and
$`g_2` is free product $`\Z/3 * \Z/4` on those generators, with no relation beyond
$`g_1^3 = g_2^4 = 1`.
:::

:::proof "thm:triangle-geometric-representation-injective"
Ping-pong, formalized in full for a free product of two finite cyclic factors. Two
disjoint nonempty subsets $`U_1, U_2 \subset \mathbb{H}` are exhibited explicitly, and
one checks the six containments $`g_1^{k} U_2 \subseteq U_1` for $`k = 1, 2` and
$`g_2^{k} U_1 \subseteq U_2` for $`k = 1, 2, 3`. The ping-pong lemma for a coproduct of
groups then makes any reduced word act nontrivially — with one wrinkle: a word beginning
and ending in the same factor has to be conjugated first, and doing so needs a third
element in that factor, supplied by the cardinality bound $`3 \le |\Z/3|`. Faithfulness
upgrades the presentation from an assertion about the abstract group to a statement
about the Fuchsian group actually acting, which is what later arguments need when they
pass between words in $`\Gamma` and transformations of $`\mathbb{H}`. $`\blacksquare`
:::

Discreteness of the corresponding matrix group is proved concretely, by exhibiting an
open neighbourhood of the identity in $`SL(2,\R)` meeting the group only in $`\pm I`.
The quantitative input is a classical inequality, which the development formalizes from
first principles.

:::theorem "thm:shimizu-leutbecher" (lean := "Mathoverflow1973.SpecialPeriods.Triangle.shimizu_leutbecher") (parent := "orbifold")
*Theorem (Shimizu–Leutbecher).* Let $`\Gamma \le SL(2,\R)` be a discrete subgroup
containing the translation matrix
$`\left(\begin{smallmatrix} 1 & w \\ 0 & 1\end{smallmatrix}\right)` for some $`w > 0`.
Then every $`A \in \Gamma` whose lower-left entry $`c` is nonzero satisfies
$`|c| \ge 1/w`. Discreteness enters as the instance `DiscreteTopology` on the subgroup
regarded as a subtype, rather than as a separation statement about its elements. Applied
to the triangle group with the cusp translation by $`w = 1 + \sqrt2`, the inequality
bounds the lower-left entries of every element away from zero — which is exactly what
keeps the horodiscs at the cusp from being moved into each other.
:::

:::theorem "thm:triangle-geometric-action-properly-discontinuous" (lean := "Mathoverflow1973.SpecialPeriods.triangleGeometricAction_properlyDiscontinuous") (parent := "orbifold") (uses := "def:triangle-geometric-representation, def:triangle-ford-region, thm:shimizu-leutbecher")
*Theorem.* The action of $`\Gamma` on $`\mathbb{H}` is properly discontinuous: for all
compact $`K, L \subset \mathbb{H}` only finitely many $`g \in \Gamma` satisfy
$`gK \cap L \neq \emptyset`.
:::

:::proof "thm:triangle-geometric-action-properly-discontinuous"
The statement is transported from the matrix group. Lifting $`\Gamma` to the subgroup of
$`SL(2,\R)` generated by $`g_1` and $`g_2` is injective, and the transporter set
upstairs is finite: an element carrying a compact set to a compact set has bounded
entries, since the imaginary part transforms by
$`\operatorname{Im}(Az) = \operatorname{Im} z/|cz+d|^2` and the Ford domain together
with the Shimizu–Leutbecher bound force the lower-left entry to be either zero or of
size at least $`1/w`. Discreteness of the matrix group then makes a bounded set of
elements finite. Pulling back along the injective lift gives the statement for
$`\Gamma`. Proper discontinuity, together with the continuity of the action, is what
makes the orbit space Hausdorff and the quotient map open — the two hypotheses under
which every quotient construction below is carried out. $`\blacksquare`
:::

:::definition "def:triangle-orbit-space" (lean := "Mathoverflow1973.SpecialPeriods.TriangleOrbitSpace") (parent := "orbifold") (uses := "thm:triangle-geometric-action-properly-discontinuous")
The orbit space $`\mathbb{H}/\Gamma` is the quotient of $`\mathbb{H}` by the orbit
relation of the geometric action. It is Hausdorff and locally compact, and the
projection is open and surjective. Two of its points are distinguished: the images of
the order-$`3` and order-$`4` fixed points, which are the cone points of the orbifold
and become $`t = 0` and $`t = 1` on the base. The action instance, the
proper-discontinuity instance and the continuity instance are attached locally at each
use site rather than globally — $`\mathbb{H}` carries several group actions in the same
module, and making any one of them a global instance would make the others unusable.
:::

:::definition "def:triangle-compactified-orbit-space" (lean := "Mathoverflow1973.SpecialPeriods.TriangleCompactifiedOrbitSpace") (parent := "orbifold") (uses := "def:triangle-orbit-space")
The compactified orbit space is the one-point compactification
$`(\mathbb{H}/\Gamma) \cup \{\infty\}`. The point at infinity is the cusp, standing for
$`p_0`; the inclusion of $`\mathbb{H}/\Gamma` is an open embedding. The resulting space
is compact and connected. As a topological space it is already the base curve of the
fibration; the work of the next three declarations is to give it a complex structure.
:::

:::definition "def:triangle-cusp-q" (lean := "Mathoverflow1973.SpecialPeriods.Triangle.cuspQ") (parent := "orbifold") (uses := "def:triangle-width")
The cusp parameter is $`q(z) = e^{2\pi i z/w}`, holomorphic and nowhere vanishing on
$`\mathbb{H}` and periodic of period $`w`, hence invariant under the cusp generator.
Since $`|q(z)| = e^{-2\pi \operatorname{Im} z/w}`, it tends to $`0` as
$`\operatorname{Im} z \to \infty` and identifies the quotient of a horodisc
$`\{\operatorname{Im} z > Y\}` by $`\langle g_0\rangle` with a punctured disc of radius
$`e^{-2\pi Y/w}`. It is the coordinate of the chart at the cusp, and the variable in
which every "regular at the cusp" condition in this chapter is stated: a function on
$`\mathbb{H}` is cusp-regular when it agrees, for $`\operatorname{Im} z` large, with
$`M(q(z))` for some $`M` analytic at the origin.
:::

:::definition "def:triangle-compactified-charted-space" (lean := "Mathoverflow1973.SpecialPeriods.triangleCompactifiedChartedSpace") (parent := "orbifold") (uses := "def:triangle-compactified-orbit-space, def:triangle-cusp-q")
The charted-space structure gives $`(\mathbb{H}/\Gamma) \cup \{\infty\}` an atlas of
$`\C`-valued charts, assembled by a branched-quotient atlas from three families. Over
the free-action locus — the complement of the two elliptic orbits — the covering
quotient descends the charts of $`\mathbb{H}` directly. At each cone point the chart is
the $`n`-th power, $`n = 3` or $`4`, of the normalized Cayley coordinate centred at the
fixed point: the branched uniformization that flattens a cone point of angle $`2\pi/n`
into a disc. At the cusp the chart sends $`\infty` to $`0` and the orbit of $`z` to
$`q(z)`. This is the object the rest of the development names when it means the base
curve; over five hundred declarations downstream refer to it.
:::

:::theorem "thm:triangle-compactified-is-manifold" (lean := "Mathoverflow1973.SpecialPeriods.triangleCompactified_isManifold") (parent := "orbifold") (uses := "def:triangle-compactified-charted-space")
*Theorem.* With that atlas, $`(\mathbb{H}/\Gamma) \cup \{\infty\}` is an analytic
complex manifold: `IsManifold 𝓘(ℂ) ω`. The model is $`\C` and the smoothness index is
$`\omega`, so the transition maps between regular, elliptic and cusp charts are
analytic, not merely continuous or differentiable — the space is a compact Riemann
surface. The content is in the transitions: a regular chart against an elliptic chart
sees the $`n`-th power map, and a regular chart against the cusp chart sees the
exponential $`q`, and both have to be checked biholomorphic where the charts overlap.
:::

Which surface it is takes one further input, and that input comes from outside the
group: the Riemann map of the hyperbolic triangle, continued across its sides by Schwarz
reflection.

:::definition "def:triangle-sphere-uniformization" (lean := "Mathoverflow1973.SpecialPeriods.Triangle.triangleSphereUniformization") (parent := "orbifold") (uses := "def:triangle-compactified-charted-space, def:triangle-signed-half-plane-map")
The uniformization is an analytic diffeomorphism — a biholomorphism, the model being
$`\C` and the smoothness index $`\omega` —
$$`(\mathbb{H}/\Gamma) \cup \{\infty\} \;\xrightarrow{\ \sim\ }\; \PP^1,`
built from the Riemann map of the hyperbolic $`(\pi/3, \pi/4, 0)` triangle continued
across its sides by Schwarz reflection, and normalized by three companion theorems: the
cusp goes to $`\infty`, the order-$`3` orbit to $`0`, the order-$`4` orbit to $`1`.
Restricted to the open part it gives $`\mathbb{H}/\Gamma \cong \C`.
:::

The base curve is therefore the projective line, with the cusp at $`\infty` and the two
cone points at $`0` and $`1`, and the affine coordinate $`t` is a genuine coordinate on
it. It is that coordinate the period functions are specified against, and they are built
upstairs on $`\mathbb{H}`, where the group acts.

# The period functions

:::group "orbifold-periods"
The three holomorphic functions $`\tau, \mu, \beta` on the upper half-plane and their
layered equivariance under $`\Gamma`, assembled into the period map of Theorem 3.4,
together with the monodromy action on the four-torus and the fundamental group of the
twice-punctured plane.
:::

The first period function is a lift through the modular $`j`-function. The modular group
plays no other role in the paper: $`\Gamma` is the $`(3,4,\infty)` triangle group and is
*not* $`PSL(2,\Z) \cong \Z/2 * \Z/3`. It enters only through the orbifold morphism
$`(\PP^1; 3,4,\infty) \to (\PP^1; 3,2,\infty)`, $`t \mapsto 1728\,t`, and it is along
the induced surjection $`\Gamma \twoheadrightarrow PSL(2,\Z)` that $`\tau` is
equivariant.

:::definition "def:special-periods-modular-j" (lean := "Mathoverflow1973.SpecialPeriods.modularJ") (parent := "orbifold-periods")
The modular $`j`-function is $`j(z) = E_4(z)^3/\Delta(z)`, built from Mathlib's
Eisenstein series of weight $`4` and the modular discriminant. The definition is that
one line; everything used about it is proved here. It is analytic on $`\mathbb{H}` and
invariant under $`SL(2,\Z)`; it takes the value $`0` at the order-$`3` elliptic point
$`\rho` and $`1728` at $`i`; it is surjective onto $`\C` and open, and injective on the
modular quotient; and it has the $`q`-expansion $`j = u(q)/q` with $`u` analytic and
nonvanishing at the origin, so a simple pole in $`q` at the cusp. The order statements
are the ones that matter below: $`j` vanishes to order $`3` on the $`\rho`-orbit and
$`j - 1728` to order $`2` on the $`i`-orbit.
:::

:::definition "def:special-periods-tau-covariant" (lean := "Mathoverflow1973.SpecialPeriods.TauCovariant") (parent := "orbifold-periods") (uses := "def:triangle-generator-one-sl, def:triangle-generator-two-sl")
A map $`\tau : \mathbb{H} \to \mathbb{H}` is covariant when
$$`\tau(g_1 z) = \frac{\tau(z) - 1}{\tau(z)}, \qquad \tau(g_2 z) = \frac{-1}{\tau(z)}`
for all $`z`, the identities being read in $`\C` after the coercion of the upper
half-plane. The two Möbius transformations on the right are the images of $`g_1, g_2`
under $`\Gamma \twoheadrightarrow PSL(2,\Z)`; composing them gives
$`\tau(g_0 z) = \tau(z) - 1`, the parabolic behaviour at the cusp. Covariance already
pins the values at the cone points: any covariant $`\tau` sends the order-$`3` fixed
point to $`\rho` and the order-$`4` fixed point to $`i`, so the paper's normalisation
$`(\tau 3)` is a consequence here, not a hypothesis.
:::

:::theorem "thm:exists-covariant-tau-of-triangle-source" (lean := "Mathoverflow1973.SpecialPeriods.exists_covariant_tau_of_triangle_source") (parent := "orbifold-periods") (uses := "def:special-periods-modular-j, def:special-periods-tau-covariant, def:triangle-width, def:cusp-uniformization-exponential, thm:exists-global-section-with-germ-of-germ-bijective")
*Theorem.* Let $`F : \mathbb{H} \to \C` be holomorphic and invariant under both
generators, with the following order data: every zero of $`F` has order divisible by
$`3`; every point where $`F = 1728` has $`F - 1728` of order divisible by $`2`; the
order at the order-$`3` fixed point is exactly $`3` and the order of $`F - 1728` at the
order-$`4` fixed point is exactly $`4`; and near the cusp $`F` agrees with $`F_c(q(z))`
for a function $`F_c` meromorphic at $`0` of order exactly $`-1`. Then there is an
analytic $`\tau : \mathbb{H} \to \mathbb{H}` with $`j \circ \tau = F`, covariant in the
sense above, sending the two cone points to $`\rho` and $`i`, and satisfying
$$`\tau(z) = \frac{z}{w} + h(q(z))`
for $`|q(z)|` small, with $`h` analytic on a disc about the origin.
:::

:::proof "thm:exists-covariant-tau-of-triangle-source"
The divisibility hypotheses are exactly the lifting criterion for the Galois covering
$`j : \mathbb{H} \smallsetminus (PSL(2,\Z)\rho \cup PSL(2,\Z)i) \to \C \smallsetminus \{0, 1728\}`:
orders divisible by $`3` at the $`j = 0` points and by $`2` at the $`j = 1728` points
kill the images of the meridians in the deck group $`\Z/2 * \Z/3`, so $`F` lifts. Rather
than classical covering-space theory, the development uses a purpose-built presheaf of
lift-sections whose germ maps are bijective; a global section of that presheaf is the
lift, and the cusp normalisation is imposed while gluing, which is where the simple pole
of $`F_c` is consumed. The lift is only determined up to the deck group, and the
equivariance is then forced rather than chosen: the induced homomorphism
$`\varphi : \Gamma \to PSL(2,\Z)` must send $`g_0` to a parabolic element, because
$`\tau` carries a cusp neighbourhood into a single component of $`\{|j| > R\}` and those
components are squeezed between horoballs; a trace computation pins $`\varphi(g_0)` to
$`T^{-1}` after normalising by a translation, and the covariance relations follow.
Uniqueness of the normalised lift comes from the triviality of the centre of
$`PSL(2,\Z)`. $`\blacksquare`
:::

Applying the theorem to $`F = 1728\,t \circ \pi`, with $`t` the affine coordinate of the
sphere uniformization, produces the $`\tau` of Theorem 3.4. The second period function
solves an affine problem over it.

:::definition "def:mu-generator-root" (lean := "Mathoverflow1973.SpecialPeriods.MuGenerator.Root") (parent := "orbifold-periods") (uses := "def:special-periods-tau-covariant, thm:exists-holomorphic-square-root-upper-half-plane")
A root for $`\tau` is a holomorphic $`r : \mathbb{H} \to \C` with
$`r(a)^2 = E_6(\tau(a))` for every $`a` — a global holomorphic square root of
$`E_6 \circ \tau`. One exists because all zeros of $`E_6 \circ \tau` have even order,
which is where the order-$`4` vanishing at the second cone point is spent, and the
square root is then produced by the analytic root-cover machinery on the simply
connected half-plane. Its purpose is the generator
$$`F = \frac{E_4(\tau)^2\, r}{\Delta(\tau)},`
which satisfies $`F(g_1 z) = -F(z)/\tau(z)` and $`F(g_2 z) = F(z)/\tau(z)`. This weight
$`-1` homogeneity, with a prescribed divisor and a simple pole in $`q`, is the concrete
stand-in for the paper's identification of the automorphy sheaf with
$`\mathcal{O}_{\PP^1}(-1)`.
:::

:::definition "def:mu-torsor-is-solution" (lean := "Mathoverflow1973.SpecialPeriods.MuTorsor.IsSolution") (parent := "orbifold-periods") (uses := "def:triangle-generator-one-sl, def:triangle-generator-two-sl, def:triangle-cusp-q")
Given $`\tau`, a function $`\mu : \mathbb{H} \to \C` is a solution when it is analytic,
satisfies the affine transformation laws
$$`\mu(g_1 z) = \frac{1 - \mu(z)}{\tau(z)}, \qquad \mu(g_2 z) = 1 + \frac{\mu(z)}{\tau(z)},`
and is cusp-regular: for $`\operatorname{Im} z` large it agrees with $`M(q(z))` for some
$`M` analytic at the origin. The laws compose to $`\mu(g_0 z) = \mu(z)`, so $`\mu`
descends near the cusp and the regularity condition is meaningful. Note that regularity
is imposed only along the filter at $`i\infty`, on the one distinguished cusp component:
the condition is not $`\Gamma`-equivariant, since $`\mu \circ g_2^2 = 1 - \tau - \mu` is
unbounded wherever $`\mu` is bounded and $`\operatorname{Im}\tau \to \infty`.
:::

:::theorem "thm:exists-unique-solution" (lean := "Mathoverflow1973.SpecialPeriods.MuTorsor.exists_unique_solution") (parent := "orbifold-periods") (uses := "def:mu-torsor-is-solution, def:mu-generator-root, def:special-periods-tau-covariant, def:special-periods-modular-j, def:triangle-cusp-q, def:riemann-sphere, thm:triangle-compactified-is-manifold, thm:triangle-geometric-representation-injective, thm:shimizu-leutbecher, thm:exists-holomorphic-square-root-upper-half-plane, thm:exists-negative-one-holomorphic-cocycle-solution")
*Theorem.* Let $`\pi` be a biholomorphism from the compactified orbit space to the
Riemann sphere carrying the cusp to $`\infty`, the order-$`3` orbit to $`0` and the
order-$`4` orbit to $`1`, and let $`\tau` be analytic and covariant with
$`j(\tau(z)) = 1728\,\pi(z)` in the affine coordinate and the expected cusp asymptotics
$`e^{2\pi i \tau(z)} = q(z)\,u(q(z))` with $`u` analytic and nonvanishing at $`0`. Then
there is a *unique* $`\mu` solving the affine problem for $`\tau`.
:::

:::proof "thm:exists-unique-solution"
Existence is a patching argument. The transformation laws define an affine cocycle on
$`\Gamma`, holomorphic in $`z`, whose linear part is the weight $`-1` factor
$`(-\tau, \tau)` at the two generators; a cover of the base by precisely invariant
patches of three kinds — one around the cusp, one at each cone point, and regular
patches elsewhere — carries obvious local solutions, namely $`\mu = 0` near the cusp and
$`\mu_1 = (2 - \tau)/3`, $`\mu_2 = (1 - \tau)/2` at the two cone points. Gluing them is
a Cousin problem for the line bundle generated by
$`E_4(\tau)^2\sqrt{E_6(\tau)}/\Delta(\tau)`, and the development solves it directly in
the weight $`-1` case rather than quoting a cohomology vanishing. Uniqueness is the
rigidity half: the difference of two solutions is homogeneous of weight $`-1` and
cusp-regular, and such a function is forced to vanish, because the quotient is compact
and the section it defines has more zeros than the degree of the bundle allows. The
values at the cone points come out as $`\mu = (2-\rho)/3` and $`\mu = (1-i)/2`, and
these are precisely the values that make the inhomogeneous terms of the $`\beta`-problem
vanish there. $`\blacksquare`
:::

:::definition "def:beta-torsor-data" (lean := "Mathoverflow1973.SpecialPeriods.BetaTorsor.Data") (parent := "orbifold-periods") (uses := "def:special-periods-tau-covariant, def:triangle-generator-one-sl, def:triangle-generator-two-sl")
The data over which $`\beta` is defined bundles an analytic
$`\tau : \mathbb{H} \to \mathbb{H}` and an analytic $`\mu : \mathbb{H} \to \C` with
$`\tau` covariant and $`\mu` satisfying the two affine laws. From such data one forms
the increments
$$`\varphi_1 = 2 - \frac{6(1-\mu)^2}{\tau}, \qquad \varphi_2 = -3 - \frac{6\mu^2}{\tau},`
and the identities $`\sum_{k<3}\varphi_1 \circ g_1^{k} = 0` and
$`\sum_{k<4}\varphi_2 \circ g_2^{k} = 0` are theorems about the data. These telescoping
sums are exactly the consistency needed for "prescribe $`\beta` and extend by the
generator laws" to be well defined on a free product of cyclic groups; with them, the
data determine an additive cocycle on $`\Gamma`.
:::

:::theorem "thm:exists-solution-with-cusp-extension" (lean := "Mathoverflow1973.SpecialPeriods.BetaTorsor.Data.exists_solution_with_cusp_extension") (parent := "orbifold-periods") (uses := "def:beta-torsor-data, def:triangle-cusp-q, def:riemann-sphere, def:triangle-compactified-charted-space, thm:shimizu-leutbecher, thm:triangle-geometric-representation-injective")
*Theorem.* For any such data and any biholomorphism from the compactified orbit space to
the Riemann sphere carrying the cusp to $`\infty`, there exist an analytic
$`\beta : \mathbb{H} \to \C` and a function $`C` analytic at the origin with $`C(0) = 0`
such that
$$`\beta(g_1 z) = \beta(z) + \varphi_1(z), \qquad \beta(g_2 z) = \beta(z) + \varphi_2(z),`
and $`\beta(z) + \tau(z) = C(q(z))` for $`\operatorname{Im} z` large. So $`\beta` solves
the additive cocycle, and $`b = \beta + \tau` — which the generator laws make invariant
under $`g_0` — extends analytically across the cusp and vanishes there.
:::

:::proof "thm:exists-solution-with-cusp-extension"
The same three-patch scheme as for $`\mu`, one degree simpler because the cocycle is
additive: the torsor is under the structure sheaf rather than under a twist. Local
solutions are immediate — $`\beta = 0` on a regular patch, $`\beta = -\tau` near the
cusp, which is why $`C(0) = 0` in the conclusion, and
$`\beta = \tfrac{1}{m}\sum_{k<m} k\,(\varphi \circ g^k)` at a cone point of order $`m`,
where the telescoping identity is what makes the average equivariant. The differences on
overlaps are invariant holomorphic functions, and the additive Cousin problem for them
is solved by the same patching machinery. Note the affine constant: adding any
$`c_0 \in \C` to $`\beta` preserves the generator laws, so the solutions form an affine
line, and the theorem asserts only that the line is nonempty and contains a member with
$`b` vanishing at the cusp. Fixing which member is used is deferred — it is the last
step in building the period map. $`\blacksquare`
:::

The three functions now exist. One further piece of the base data is exported before
they are packaged: the action carrying the monodromy of the torus fibres.

:::definition "def:triangle-torus-action" (lean := "Mathoverflow1973.SpecialPeriods.triangleTorusAction") (parent := "orbifold-periods") (uses := "def:special-periods-triangle-group, def:lattice, def:t")
The monodromy action is an action of $`\Gamma` on the real four-torus $`\R^4/\Z^4`. It
comes from the lattice representation $`\Gamma \to SL(4,\Z)`, $`g_1 \mapsto T_1`,
$`g_2 \mapsto T_2`, composed with the contragredient $`T \mapsto (T^{-1})^{\mathsf T}`;
the resulting matrices are the $`A_1, A_2` acting on the dual lattice, with unipotent
value $`M_0` at the cusp generator and the relation $`A_1 A_2 M_0 = I` matching
$`g_1 g_2 g_0 = 1`. Integrality means the standard lattice is preserved, so each matrix
descends to a homeomorphism of the torus fixing the origin, and
$`g \cdot [x] = [A_g x]`. This is the flat real trivialisation in which the family's
monodromy is used downstream: the group acts on the fibre by a constant integral matrix,
independently of the point of the base.
:::


:::definition "def:special-period-map" (lean := "Mathoverflow1973.SpecialPeriods.specialPeriodMap") (parent := "orbifold-periods") (uses := "def:holomorphic-period-map, def:triangle-sphere-uniformization, thm:exists-period-functions-of-sphere")
The period map assigns to each $`z \in \mathbb{H}` the period point
$`(\tau(z), \mu(z), \beta(z))`, with the three coordinates analytic in $`z` and the
point *admissible*: $`\operatorname{Im}\tau > 0` and
$$`D = \operatorname{Im}\beta - \frac{6(\operatorname{Im}\mu)^2}{\operatorname{Im}\tau} < 0,`
the condition under which the period matrix
$`\left(\begin{smallmatrix} 6\mu & \tau & 1 & 0 \\ \beta & \mu & 0 & 1\end{smallmatrix}\right)`
has nonzero real determinant and so spans a genuine lattice in $`\C^2`. It is built from
the normalized sphere uniformization by running the three constructions in order — the
$`\tau`-lift through $`j`, the unique $`\mu`, the glued $`\beta` — and then fixing the
additive constant: the constant used is purely imaginary with sufficiently negative
imaginary part, which is available because $`D` is $`\Gamma`-invariant, continuous away
from the cusp and tends to $`-\infty` there. This is Theorem 3.4 of {citet alpoge.s6}[].
:::

:::theorem "thm:special-period-map-generator" (lean := "Mathoverflow1973.SpecialPeriods.specialPeriodMap_generator₁") (parent := "orbifold-periods") (uses := "def:special-period-map, def:triangle-generator-one-sl, def:triangle-generator-two-sl, thm:exists-period-functions-of-sphere")
*Theorem.* The period map is equivariant: $`p(g_1 \cdot z) = p(z).\mathrm{step}_1`, and,
in the companion statement for the second generator,
$`p(g_2 \cdot z) = p(z).\mathrm{step}_2`, where
$$`\mathrm{step}_1(\tau,\mu,\beta) = \Big(\tfrac{\tau-1}{\tau},\ \tfrac{1-\mu}{\tau},\ \beta + 2 - \tfrac{6(1-\mu)^2}{\tau}\Big),`
$$`\mathrm{step}_2(\tau,\mu,\beta) = \Big(\tfrac{-1}{\tau},\ 1 + \tfrac{\mu}{\tau},\ \beta - 3 - \tfrac{6\mu^2}{\tau}\Big).`
The two steps are the layered equivariance of the three functions read as a single
transformation of the period point.
:::

:::proof "thm:special-period-map-generator"
Coordinatewise, this is exactly the definition of the three transformation laws:
$`\mathrm{step}_1` and $`\mathrm{step}_2` are the covariance of $`\tau`, the affine laws
of $`\mu`, and the additive increments $`\varphi_1, \varphi_2` of $`\beta` written in
one line. The only content beyond bookkeeping is that the additive shift used to make
the period point admissible is a constant, hence commutes with the increments, so
equivariance survives the normalisation. What the statement buys is the geometry: the
period matrix satisfies $`\Pi(gz) = R_g(z)\Pi(z)M_g` with $`R_g` invertible and
cocyclic, and $`R_{g_0} = I`; so the group acts on the total space of the torus family
by fibre-preserving biholomorphisms, freely away from the two elliptic orbits, and the
quotient is a family of two-tori over the thrice-punctured line with monodromy
$`A_1, A_2, M_0` on the marked $`H_1`. $`\blacksquare`
:::

The last two declarations of this cluster are topological, and they are consumed much
later: the base minus its three special points is identified with
$`\C \smallsetminus \{0,1\}` through the uniformization, and its fundamental group is
computed.

:::definition "def:twice-punctured-fundamental-group-free-equiv" (lean := "Mathoverflow1973.SpecialPeriods.Triangle.twicePuncturedFundamentalGroupFreeEquiv") (parent := "orbifold-periods")
A group isomorphism
$$`\pi_1(\C \smallsetminus \{0,1\}, \tfrac12) \;\cong\; F_2,`
from the fundamental group of the twice-punctured plane, based at $`1/2`, to the free
group on `Bool`. Its inverse sends the two free generators to the positive meridians
around $`0` and $`1`. Rather than Seifert–van Kampen, the proof runs an explicit
two-slit open cover of the punctured plane with locally constant free-group-valued
transition functions; a loop is read off as a word by recording the sequence of slits it
crosses, and the two directions of the bijection are the word map and its inverse.
:::

:::theorem "thm:positive-outer-meridian-class-eq" (lean := "Mathoverflow1973.SpecialPeriods.Triangle.positiveOuterMeridian_class_eq") (parent := "orbifold-periods") (uses := "def:twice-punctured-fundamental-group-free-equiv")
*Theorem.* For $`R \ge 2`, the class of the positively oriented circle of radius $`R` in
$`\pi_1(\C \smallsetminus \{0,1\})` is the product of the two meridians, in that order.
Both sides are pushed through the free-group isomorphism, where the claim becomes an
identity between explicit words. This is the boundary-of-a-disc-at-infinity relation:
the loop around both punctures at once is the loop around $`0` followed by the loop
around $`1`, matching $`g_1 g_2 g_0 = 1` in $`\Gamma`. It is the input to the van Kampen
computation of the fundamental group of the threefold, where the third meridian — the
one at the cusp — is what the toric filling kills.
:::
