/-
Copyright (c) 2026 Eric Vergo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Eric Vergo, Claude Fable 5 (Claude Code)
-/
/-
Hopf problem blueprint — Proof overview chapter.

The curated coarse layer over the 429-node blueprint: fifteen milestones in paper order,
each an informal sketch of one stage of Alpöge's argument together with the nodes that
formalize it.
-/

import Verso
import VersoManual
import VersoBlueprint
import Macros
import Bibliography
import Solution

open Verso.Genre
open Verso.Genre.Manual hiding citep citet citehere
open Informal

set_option doc.verso true
set_option verso.blueprint.trimTeXLabelPrefix true
set_option pp.rawOnError true

#doc (Manual) "Proof overview" =>

The construction starts from a rank-four lattice carrying two automorphisms of orders
$`3` and $`4` whose product's inverse is unipotent, and from the $`(3,4,\infty)`
orbifold — the projective line with two cone points and a cusp — whose orbifold
fundamental group is the triangle group $`\Z/3 * \Z/4`. Three explicit holomorphic
functions $`\tau, \mu, \beta` on the upper half-plane, characterized by inhomogeneous
transformation laws under that group together with one negativity condition, assemble
into a $`2 \times 4` period matrix; its columns span a lattice in $`\C^2`, and the
quotient is a holomorphic family $`J` of complex $`2`-tori over the thrice-punctured
line, the lattice $`\Lambda` marking the first homology of every fibre and the matrices
$`A_1, A_2, M_0` acting as the monodromies around the three punctures. This is the $`(3,4,\infty)`
modular family of the title: the analogue of a universal family of abelian surfaces over
a modular curve, with a rank-four monodromy representation in place of a symplectic one,
and — deliberately — no polarization anywhere.

The family is completed over the three special points by three classical local models. At
the cusp, a Mumford toroidal degeneration: an infinite smooth toric threefold over the
$`A_2` triangulation of the plane, divided by a twisted $`\Z^2`-action, whose central
fibre $`W` is a single degree-six del Pezzo surface with the three pairs of opposite
sides of its hexagon of $`(-1)`-curves identified. At the two cone points, Kodaira
logarithmic transforms of multiplicities $`3` and $`4` — quotients by a rotation of the
base twisted by a translation of the fibre — whose reduced central fibres are bielliptic
surfaces. Gluing the four pieces gives a compact complex threefold $`X` fibred by tori
over $`\PP^1`, and its topology is then the arithmetic of three integers
$`(\ell_0,\ell_1,\ell_2) = (0,1,-1)`: van Kampen gives
$`\pi_1(X) \cong \Z/|12\ell_0 - 4\ell_1 - 3\ell_2| = 1`, and Mayer–Vietoris gives
$`H_*(X;\Z) \cong H_*(S^6;\Z)`. A closed simply connected six-manifold with that homology
is homotopy equivalent to $`S^6` by Hurewicz and Whitehead, hence homeomorphic to it by
Smale; transporting the holomorphic atlas of $`X` along the homeomorphism answers Hopf's
question.

This page is a hand-authored map of that argument rather than a generated one. Each
milestone below is one stage of the proof: a title, the section of {citet alpoge.s6}[] it
corresponds to, an informal sketch, and the nodes of this blueprint that formalize it.
The nodes are the authority — the sketches are prose, and where a sketch and a node
disagree it is the node that was proved. The arrows between milestones are checked
against the machine dependency graph of the nodes: an arrow is drawn solid when some node
of the target milestone actually depends on some node of the source, and dashed when the
dependency is mathematical rather than formal — a stage whose conclusions enter the next
one as hypotheses supplied at the point of application rather than as inputs to its proof
terms. Two milestones have no counterpart construction in the paper at all: singular
homology and Morse theory, which the paper cites as standard and the Lean development
builds from nothing. Their section references point at where the paper uses them.

:::milestone "ms:lattice" (title := "The lattice and its monodromy") (paper := "§2") (paper_url := "https://alpo.ge/s6.pdf") (members := "def:lattice, def:t, def:t-two, def:t-zero, thm:t-cube, thm:t-fourth, def:a, def:a-two, def:m, def:gamma, def:epsilon, thm:a-fixed-iff, thm:m-sub-one-range, def:b-zero, def:exterior-square, def:exterior-cube")
Everything discrete in the construction is generated by two integer matrices. On the
rank-four lattice $`V = \Z^4` with basis $`(\gamma, u, w, \delta)` the matrices $`T_1` and
$`T_2` have exact orders $`3` and $`4`, and the inverse of their product,
$`T_0 = (T_1T_2)^{-1}`, is unipotent with $`N = T_0 - I` of square zero: the
$`(3,4,\infty)` pattern of local monodromies, finite at the two cone points and parabolic
at the cusp. The dual action on $`\Lambda = V^*` is by the contragredients
$`A_j = (T_j^{-1})^t` and $`M_0`, and the coordinate functional $`\gamma\colon\Lambda\to\Z`
is fixed by all of them, which is what makes the twist invariants $`\ell_j = \gamma(v_j)`
well defined. At the cusp kernel and image coincide,
$`\ker(M_0 - I) = \operatorname{im}(M_0 - I) = \Lambda_{\mathrm{tor}} = \langle\hat w,\hat\delta\rangle`,
and the induced map $`B_0 \colon \Lambda/\Lambda_{\mathrm{tor}} \to \Lambda_{\mathrm{tor}}`
is unimodular — the one arithmetic fact that later forces the cusp fibre to be
irreducible, with a single del Pezzo surface as its normalization rather than several.
The fixed sublattices $`\Lambda^{A_1} = \langle\varepsilon,\hat\delta\rangle` and
$`\Lambda^{A_2} = \langle\varepsilon',\hat\delta\rangle` supply the twist vectors, and the
exterior square and cube of each matrix supply the monodromy action on the higher homology
of the fibre. In Lean all of this is literal matrices and the ledger is decided by
computation.
:::

:::milestone "ms:uniformization" (title := "Uniformizing the base orbifold") (paper := "§2.5") (paper_url := "https://alpo.ge/s6.pdf") (members := "thm:eq-on-zero-or-forall-ne-zero-of-tendsto-locally-uniformly-on, thm:exists-bij-on-unit-ball-deriv-ne-zero-map-eq-zero, def:biholomorph-unit-disc, thm:exists-analytic-extension-of-modulus-one, def:riemann-mapping-triangle-map, def:triangle-closed-disc-homeomorph, def:triangle-signed-half-plane-map, def:quotient-biholomorph, def:compactified-biholomorph, thm:exists-global-section-with-germ-of-germ-bijective, thm:exists-analytic-square-root-on-of-even-zeros, def:riemann-sphere, def:special-periods-triangle-group, def:triangle-geometric-representation, thm:triangle-geometric-representation-injective, thm:shimizu-leutbecher, thm:triangle-geometric-action-properly-discontinuous, def:triangle-ford-region, def:triangle-orbit-space, def:triangle-compactified-orbit-space, thm:triangle-compactified-is-manifold, def:triangle-sphere-uniformization")
The base of the fibration is the $`(3,4,\infty)` orbifold: the projective line with cone
points of orders $`3` and $`4` and one cusp. The group is defined abstractly, as the free
product $`\Z/3 * \Z/4`, and made to act on the upper half-plane by two explicit elements
of $`SL(2,\R)` of cusp width $`1 + \sqrt2`; injectivity of that geometric representation
and proper discontinuity of the action are read off a Ford fundamental region, the second
through Shimizu–Leutbecher. The uniformization is then built rather than quoted: a Riemann
map of the open Ford triangle, extended across the boundary by Schwarz reflection and a
boundary-correspondence argument to a homeomorphism of closed discs, is post-composed with
a cross-ratio and descends to a biholomorphism from the one-point-compactified quotient
$`\mathbb{H}/\Gamma \cup \{\infty\}` onto $`\PP^1`, the cusp going to $`\infty` and the two
cone points to $`0` and $`1`. Along the way the development needs Hurwitz's theorem for
the limit of the Riemann-mapping extremal sequence, a monodromy principle continuing
germs of a local predicate over a simply connected base, and the existence of holomorphic
square roots on domains where every zero has even order — the last because the modular
construction of the period functions uses $`E_6^{1/2}\circ\tau`. None of this involves the
lattice: it is the analytic ground over which the period functions are solved.
:::

:::milestone "ms:period-family" (title := "The period family") (paper := "§3") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:lattice, ms:uniformization") (members := "def:special-periods-modular-j, def:special-periods-tau-covariant, thm:exists-covariant-tau-of-triangle-source, def:mu-generator-root, def:mu-torsor-is-solution, thm:exists-unique-solution, def:beta-torsor-data, thm:exists-solution-with-cusp-extension, def:special-period-map, thm:special-period-map-generator, def:triangle-torus-action, def:period-point, def:period-domain, def:holomorphic-period-map, def:period-family-data, thm:data-matrix-covariance, thm:data-is-manifold-3, def:period-family-regular-data, def:period-functions, thm:exists-period-functions-of-sphere")
Three holomorphic functions on the upper half-plane carry the entire family. The first,
$`\tau`, is pinned by $`j(\tau) = 1728\,t\circ\pi` together with the covariance
$`\tau\circ g_1 = (\tau-1)/\tau`, $`\tau\circ g_2 = -1/\tau`; the other two solve
inhomogeneous versions of the same laws, $`\mu` as the unique solution of a torsor problem
under a line bundle isomorphic to $`\mathcal{O}_{\PP^1}(-1)`, whose cohomology vanishes in
both degrees, and $`\beta` as a solution of a torsor problem under $`\mathcal{O}`, where
$`H^1` vanishes and $`H^0 = \C` leaves exactly one additive constant $`c_0` of freedom.
They assemble into the period matrix $`\Pi = [\,Z \mid I\,]` with
$$`Z = \begin{pmatrix} 6\mu & \tau \\ \beta & \mu \end{pmatrix},`
and the discriminant condition
$`\operatorname{Im}\beta - 6(\operatorname{Im}\mu)^2/\operatorname{Im}\tau < 0`, arranged by
taking $`\operatorname{Im}c_0` sufficiently negative, is precisely what makes
$`\Pi(z)\Lambda` a lattice in $`\C^2` at every point. Quotienting the resulting family of
complex $`2`-tori by the triangle group — acting on the base by deck transformations and
on the fibres through the cocycle $`R_g` determined by $`\Pi(gz) = R_g(z)\Pi(z)M_g` — gives
a holomorphic family $`J \to B^\circ` over the thrice-punctured line, with $`H_1` of each
fibre marked by $`\Lambda` and monodromies $`A_1, A_2, M_0` around the punctures. The Lean
development keeps the period point abstract, as an admissible triple
$`(\tau,\mu,\beta)`, so that the family, its manifold structure and its topology are
proved once and instantiated at the specific solution afterwards.
:::

:::milestone "ms:toric-filling" (title := "Filling the cusp") (paper := "§4") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:lattice") (members := "def:toric-fan-triangle, def:triangle-rays, thm:triangle-rays-det, def:toric-space-space, def:toric-space-is-manifold, def:toric-space-time, def:toric-space-ray-divisor, thm:toric-space-ray-divisor-inter-nonempty-iff, def:logarithmic-period, def:twisted-translate, def:toric-space-small-drift, thm:cusp-quotient-proper-action, thm:cusp-quotient-free-action, def:cusp-quotient-quotient-space, thm:cusp-quotient-is-manifold, def:cusp-quotient-projection, thm:cusp-quotient-base-map-proper, thm:exists-admissible-radius, def:cusp-honeycomb-tiling-base-cell, def:compatible-cell-homeomorph, thm:compatible-cell-homeomorph-opposite, thm:cusp-quotient-tube-simply-connected, def:fundamental-group-equiv, def:total-uniformization-biholomorph")
Over the cusp the fibres degenerate and the filling is Mumford's. On the $`A_2`
triangulation of $`\R^2` — vertices $`\Z^2`, cells cut out by $`y_1, y_2, y_1 + y_2 \in \Z`
— the cones over the cells at height one form a fan all of whose members are unimodular,
so the associated infinite-type toric threefold $`Y` is a smooth complex manifold carrying
a global holomorphic function that reads $`z_0z_1z_2` in every triangle chart. The lattice
$`\overline\Lambda \cong \Z^2` acts on the tube $`\{|t| < \varepsilon\}` by twisted
translations $`\Psi_v(x,t) = (c_v(t)\,t^{B_0 v}x,\; t)`, the twist coming from the cusp
expansion $`Z(s) = sB_0 + C(t_c)` of the periods; a drift estimate on $`C` makes the action
free and properly discontinuous once $`\varepsilon` is small, and the quotient $`N_0` is a
complex threefold with a proper map to the disc. Its fibres away from the origin are the
tori of the period family, and its central fibre is the normal-crossings surface $`W`:
one degree-six del Pezzo with the three pairs of opposite sides of its hexagon of
$`(-1)`-curves glued, three rational double curves, two triple points — irreducible
because $`B_0` is unimodular, so that the lattice permutes the toric divisors simply
transitively. The tube upstairs is simply connected, which makes the quotient map a
universal covering and gives $`\pi_1(N_0) \cong \overline\Lambda \cong \Z^2`: the vanishing
cycles $`\Lambda_{\mathrm{tor}}` die in the filling, which is what the van Kampen
computation needs from this stage.
:::

:::milestone "ms:log-transforms" (title := "Filling the elliptic points") (paper := "§5") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:lattice, ms:period-family") (members := "def:elliptic-kind, def:elliptic-flat-affine, def:admissible-twist, thm:main-twist-admissible, thm:flat-affine-free-iff, def:fixed-period, def:flat-torus-affine, def:elliptic-surface, def:elliptic-filling, def:filling-projection, thm:filling-projection-fibre-connected, def:equivariant-data, thm:data-is-manifold-2, def:log-gauge-gauge-map, def:main-filling-to-tautological-biholomorph, thm:coinvariant-map-ker-eq-range, thm:deck-generator-pow-order, def:surface-fundamental-group-deck-equiv, thm:surface-fundamental-group-deck-equiv-log-meridian, def:fibre-matrix")
At the two cone points the local monodromy has finite order $`m_j \in \{3,4\}` and the
filling is a Kodaira logarithmic transform. On the local family over a disc the deck
transformation is twisted: in flat coordinates it is
$`(z,x) \mapsto (g_jz,\; A_jx + v_j/m_j)` for a twist vector $`v_j` fixed by $`A_j`. The
generated $`\Z/m_j`-action is free exactly when $`3 \nmid \gamma(v_1)`, respectively
$`\gamma(v_2)` odd — a fixed-point criterion for affine self-maps of a torus, reduced to
two congruences on the functionals $`\gamma` and $`\psi_j` that $`A_j` fixes — and the
choices $`v_1 = \varepsilon`, $`v_2 = -\varepsilon'` give $`(\ell_1,\ell_2) = (1,-1)`, both
admissible. The quotient $`N_j` is a complex threefold whose map to the disc has the
multiple fibre $`m_jS_j`, with $`S_j` a free cyclic quotient of an abelian surface: a
bielliptic surface, with torsion-free $`H_1 \cong \Z^2` and fundamental group the affine
crystallographic group generated by $`\Lambda` and one element whose $`m_j`-th power is
translation by $`v_j`. Translating fibrewise by the logarithmic section
$`\frac{\log s_j}{2\pi i}\,\Pi v_j` conjugates the twisted deck map back to the tautological
one, and so identifies $`N_j` minus its central surface with the part of the period family
it replaces — the gluing datum the assembly consumes, and the source of the meridian
relation that later fixes $`\pi_1`.
:::

:::milestone "ms:threefold" (title := "Assembling the threefold") (paper := "§6") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:period-family, ms:toric-filling, ms:log-transforms") (members := "def:cusp-family-log-base, def:cusp-family-data, def:threefold-puncture, def:threefold-base-cover, def:special-regular-family, def:elliptic-filling-filling-space, def:special-elliptic-piece, def:threefold-cusp-model-equiv, def:star-input, def:special-cusp-piece, def:threefold-local-piece, thm:cusp-global-overlap-sphere-period-agreement, def:threefold-local-overlap, def:threefold-space, def:threefold-charted-space, def:threefold-projection, thm:threefold-space-compact, thm:space-is-manifold, thm:threefold-real-dimension, def:threefold-gluing-data, thm:data-is-manifold")
$`X` is the four pieces glued along their collars: the torus family over the
thrice-punctured base, the toric filling at the cusp, and the two logarithmic fillings,
identified over the punctured coordinate discs by the three regluing biholomorphisms. The
Lean development performs the gluing through a general star-shaped datum — an open cover
of the base indexed by the punctures together with one outer patch, one space over each
patch, and one overlap diffeomorphism per filling — so that the Hausdorff and
charted-space structures, and the theorem that an analytic atlas on each piece glues to
an analytic atlas on the total space, are proved once for the pattern and instantiated.
Properness of $`f\colon X \to B` is local on the base and holds patch by patch, and with
$`B` compact this gives $`X` compact; the model space is $`\C\times\C^2`, so $`X` is a
complex threefold whose underlying real dimension is $`6`. One agreement statement carries
real weight: the cusp piece is manufactured from a correction matrix $`C`, and the periods
of the global family over the cusp disc must be exactly the periods $`sB_0 + C(t_c)` that
$`C` encodes, or the tautological identification at the cusp would be gluing two different
families. Independence of the auxiliary choices — radii, branches of logarithm,
linearizing coordinates — is what makes it legitimate to speak of *the* threefold; the
one genuine parameter that survives is the constant $`c_0` of the period problem.
:::

:::milestone "ms:homology-theory" (title := "Homology from scratch") (paper := "§7") (paper_url := "https://alpo.ge/s6.pdf") (members := "def:singular-complex, def:singular-homology, def:singular-homology-map, def:singular-mayer-vietoris-small-complex, thm:chain-sequence-short-exact, def:formal-subdivision, thm:small-inclusion-quasi-iso, def:connecting-homomorphism, thm:exact-at-intersection, thm:singular-mayer-vietoris-exact-at-pair, thm:exact-at-ambient, def:first-hurewicz-equiv, def:singular-h1-equiv-of-pi1, def:sphere-homology-unit-sphere, def:suspension-sphere-homeomorph, def:unit-sphere-homology-suspension-equiv, def:unit-sphere-homology-top-equiv, def:unit-sphere-top-class, thm:unit-sphere-homology-subsingleton, thm:unit-sphere-simply-connected-space")
Integral singular homology of topological spaces does not exist in Mathlib, and the
computation the paper performs needs it with named maps and a usable Mayer–Vietoris
sequence, so the development builds it. Chains are the Moore complex of Mathlib's singular
simplicial set with coefficients in $`\Z`; the Mayer–Vietoris sequence of an open two-set
cover comes from the short exact sequence relating small chains to the chains of the two
pieces, together with the small-simplices theorem, which is proved through a purely
combinatorial barycentric subdivision on formal chains over a vertex set with an explicit
mesh estimate. Degree one is tied back to the fundamental group by an explicit Hurewicz
isomorphism $`\pi_1(X,b)^{\mathrm{ab}} \cong H_1(X;\Z)`, in the form the rest of the
development calls: if $`\pi_1` is isomorphic to a given abelian group, so is $`H_1`. The
homology of spheres is then a suspension induction from the circle: the homeomorphism
$`\Sigma S^n \cong S^{n+1}` gives the suspension isomorphism, $`H_{n+1}(S^{n+1};\Z) \cong \Z` with a named
fundamental class, and everything in between vanishes. The paper takes all of this as
standard and cites Hatcher; the section reference above points at where it is used.
:::

:::milestone "ms:pieces-homology" (title := "The homology of the pieces") (paper := "App. A") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:homology-theory, ms:period-family, ms:toric-filling, ms:log-transforms") (members := "def:product-torus-homology-equiv, thm:product-torus-homology-finrank, def:coordinate-h1-four-equiv, def:coordinate-torus-h2-exterior-equiv, def:coordinate-torus-h3-exterior-equiv, thm:standard-exterior-map-coefficient, def:product-torus-top-class, def:mapping-torus-torus, def:mapping-torus-homology-wang-boundary, thm:wang-exact-at-fibre, thm:wang-boundary-product-cover, def:piece-mapping-torus-homotopy-equiv, def:surface-mapping-torus-homeomorph, def:surface-homology-coordinates, thm:period-cover-h1-ker-eq-deck-difference-range, def:source-difference, def:source-kernel-projection, thm:source-coinvariant-inclusion-kernel-projection-exact, def:family-homology-equiv, def:boundary-cap-kernel-equiv, def:unit-cap-section-class, thm:elliptic-boundary-source-kernel-projection, thm:boundary-source-kernel-projection, thm:reference-classes-regular")
Every piece of $`X`, and every collar between pieces, is up to homotopy either a torus, a
mapping torus of an integral matrix acting on one, or a free finite quotient of such. The
homology of $`T^r = (\R/\Z)^r` is computed by induction on circle factors, giving
$`H_n(T^r;\Z) \cong \Z^{\binom{r}{n}}` and, for the fibre four-torus, the exterior-algebra
markings $`H_1 \cong \Lambda`, $`H_2 \cong \bigwedge^2\Lambda`,
$`H_3 \cong \bigwedge^3\Lambda`, under which an integral matrix acts by its minors — which
is why the lattice stage records the exterior square and cube of the monodromies. Each
punctured local piece is homotopy equivalent to the mapping torus of its local monodromy,
and the Wang sequence of a mapping torus converts that into the exact sequence relating
the homology of the collar to the cokernel and kernel of $`f_* - 1` on the fibre. The same
pattern computes the homology of the open family: a Wang-type sequence for the difference
operator $`\delta_n(x,y) = ((A_1)_* - 1)x + ((A_2)_* - 1)y` over the free group of the
twice-punctured base, giving $`H_*(J;\Z)` with Betti numbers $`(1,3,6,8,6,2)`. The
bielliptic fibres appear as mapping tori of an order-$`m_j` self-map of $`T^3`, with
torsion-free homology $`(\Z,\Z^2,\Z^2,\Z^2,\Z)`, and the cap-kernel statements record which
classes on each boundary five-manifold die in the filling behind it — the bookkeeping the
global Mayer–Vietoris consumes.
:::

:::milestone "ms:cusp-fibre" (title := "Collapsing onto the cusp fibre") (paper := "§7.2") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:toric-filling, ms:homology-theory, ms:pieces-homology") (members := "def:quotient-central-fibre, def:cusp-retraction-change-twist, def:cusp-positive-positive-twist, thm:exists-closed-quotient-strong-deformation-retraction, thm:exists-closed-quotient-controlled-strong-deformation-retraction, def:actual-quotient-fibre, def:prescribed-actual-fibre-collapse, thm:exists-controlled-actual-fibre-retraction, def:marked-collapse, thm:exists-original-marked-specialization-models, thm:exists-controlled-retraction-all-levels, def:fundamental-cell, def:fundamental-cell-map, def:cusp-central-homology-central-betti, def:central-singular-homology-equiv, def:base-torus-projection, thm:marked-collapse-homology-surjective, thm:marked-collapse-homology-kernel, thm:exists-actual-specialization-homology, thm:central-homology-four-map-eq-zero-of-base-first-zero, def:cusp-boundary-gamma-zero-boundary, def:cusp-boundary-gamma-zero-native-class, thm:gamma-boundary-to-full-homology-four-eq-zero, thm:boundary-filling-homology-map-native-class-eq-zero")
What the cusp filling has to contribute to the global computation is a retraction together
with an explicit collapse map. The closed tube around the central fibre strong-deformation
retracts onto $`W`, and the retraction can be forced to realize a prescribed map on any
chosen level of the tube: the construction is run first for a constant, purely imaginary
period matrix, where the deck action preserves the positive orthant of every toric chart
and the quotient is organized by the honeycomb dual to the $`A_2` triangulation, and is
then transported back to the actual twist by a gauge change and a polar decomposition. On
a nearby fibre — a four-torus in its $`\Lambda`-marking — the resulting collapse crushes
the fibre torus to a triple point of $`W` over each vertex of the dual graph, crushes one
circle onto a rational double curve over the interior of each edge, and is injective
elsewhere. It is surjective on homology in every degree, with kernel exactly the image of
$`(M_0)_* - 1`, which identifies $`H_*(W;\Z)` with the monodromy coinvariants of the nearby
torus and yields the Betti numbers $`(1,2,4,2,1)`. The last statement of the stage is a
vanishing rather than a computation: the fundamental four-cycle of the cusp boundary
bounds in the filling, which is what closes the degree-four step of the homology of $`X`.
:::

:::milestone "ms:pi1" (title := "The fundamental group is trivial") (paper := "§7.5") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:period-family, ms:toric-filling, ms:log-transforms, ms:threefold") (members := "def:local-path-value, thm:exists-path-subdivision, thm:local-path-value-exists-primitive, thm:value-eq-of-homotopy-of-open-cover, def:fundamental-group-van-kampen-two-open-cover, def:two-open-cover-lift, thm:two-open-cover-hom-ext, def:two-open-cover-pushout-equiv, thm:inclusion-hom-u-surjective-of-overlap-hom-v-surjective, thm:main-group-trivial, thm:simply-connected-space-of-open-cover, def:twist-order, def:compatible-regular-meridian-class, def:fundamental-group-free-semidirect-equiv, def:marked-regular-fundamental-group-equiv, def:twice-punctured-fundamental-group-free-equiv, thm:positive-outer-meridian-class-eq, thm:trivial-of-oriented-elliptic-power-relations, thm:pi-one-meridian-first-cube, thm:pi-one-meridian-second-fourth, thm:space-simply-connected")
Simple connectivity of $`X` is the arithmetic of the three twist integers. Seifert–van
Kampen is proved from scratch for a two-open cover, by continuing a locally defined
group-valued invariant of paths along an arbitrary path and checking that it is unchanged
by homotopies within a chart, and it is then applied in stages to the cover of $`X` by the
regular family and the three fillings. The zero section splits the fundamental group of
the open family as $`\Z^4 \rtimes F_2`, with the two free generators the marked meridians
of the base and the semidirect product taken along $`A_1` and $`A_2`; filling the cusp
kills $`\Lambda_{\mathrm{tor}}` together with the toric meridian, and filling at the cone
point of order $`m_j` imposes that the $`m_j`-th power of the elliptic meridian is
translation by $`v_j`. What survives is the presentation
$$`\langle\, c,\, x,\, y \;\mid\; c\ \text{central},\ xy = c^{\ell_0},\ x^3 = c^{\ell_1},\ y^4 = c^{\ell_2} \,\rangle,`
an abelian group of order $`|12\ell_0 - 4\ell_1 - 3\ell_2|`. For the tautological gluing at
the cusp and the twist vectors $`v_1 = \varepsilon`, $`v_2 = -\varepsilon'` the triple is
$`(0,1,-1)`, the order is $`|-4 + 3| = 1`, and $`\pi_1(X) = 1`; the sign of $`\ell_2` is
not decoration — the same construction with $`v_2 = +\varepsilon'` gives $`\Z/7`.
:::

:::milestone "ms:homology-x" (title := "The homology of a six-sphere") (paper := "§7.6") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:threefold, ms:pieces-homology, ms:cusp-fibre, ms:pi1") (members := "def:sigma-homology-equiv, def:star-fillings, def:star-left-homology-map, def:star-connecting-homomorphism, thm:star-exact-at-pair, thm:star-exact-at-ambient, thm:boundary-filling-homology-map-surjective, thm:regular-inclusion-kernel, def:native-cap-kernel, thm:wang-cancellation, thm:homology-subsingleton-of-lt, thm:star-left-one-bijective, thm:homology-two-generator-eq-zero, thm:homology-two-subsingleton, thm:reference-fibre-coefficient-eq-one, thm:homology-three-subsingleton, thm:homology-four-subsingleton, def:fifth-wang-coordinate, thm:homology-five-subsingleton, def:homology-six-equiv, def:top-degree-top-class")
The global computation is a single Mayer–Vietoris sequence, run in the star-shaped form
the gluing already provides: the regular family against the disjoint union of the three
fillings, with the three collars as the overlap, additivity of homology over the finite
disjoint union turning the three-fold cover into a two-set one. Exactness at the pair term
and at the ambient term is proved once for the star pattern, and the degrees are then
settled one at a time against the local data. Degree $`1` is bijectivity of the difference
map, which needs $`H_1(X;\Z) = 0` and so rests on simple connectivity through the
degree-one Hurewicz isomorphism; degree $`2` produces a single generator, killed by a
Bézout identity between the multiplicities — sweeping in the multiplicity-three fibre kills
twice the generator, sweeping in the multiplicity-four fibre kills three times it, and
$`3 - 2 = 1`. Degrees $`3` and $`4` reduce to one integer coefficient, forced to be a unit
by the cap-kernel bookkeeping together with the vanishing of the cusp boundary's top class
in its filling, and degree $`5` reduces to a single Wang coordinate; everything above
degree $`6` vanishes because the pieces are homotopy equivalent to compact objects of real
dimension at most four. What is left is $`H_*(X;\Z) \cong H_*(S^6;\Z)`, with a named
fundamental class in degree $`6`.
:::

:::milestone "ms:morse-theory" (title := "The Morse-theoretic machinery") (paper := "§8") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:homology-theory") (members := "def:manifold-morse-is-morse, def:critical-points, thm:exists-signed-morse-chart-of-cont-diff-on, def:signed-morse-chart, thm:nonempty-signed-morse-chart, thm:exists-morse-function-with-distinct-critical-values, thm:exists-adapted-descent-field, def:flow-construction-compact-flow, thm:exists-adapted-descent-flow, thm:cont-mdiff-native-flow, def:morse-handle-model-map, def:morse-handle-descent-flow, def:morse-surgery-data, thm:exists-morse-surgery-data-lt, def:surgery-windows, thm:nonempty-surgery-windows, def:adapted-windows, thm:morse-exact-at-lower, thm:regular-level-is-manifold, thm:exists-regular-sublevel-homotopy-equiv, thm:nonempty-regular-level-homeomorph, thm:not-surjective-cont-mdiff-of-dim-lt, thm:exists-relative-embedded-avoidance-in-open, thm:exists-rank-three-relative-cancellation")
The paper quotes Smale's theorem; the development proves it, and that begins with building
Morse theory on manifolds charted on a real normed space. A function is Morse when every
point admits a smooth chart in which it is a nondegenerate diagonal quadratic form plus a
constant; the Morse lemma is established on the chart level and transported, Morse
functions with pairwise distinct critical values are produced on compact manifolds, and a
gradient-like field with its global flow follows from compactness. Around each critical
point sits a surgery datum — the model handle $`D^\lambda \times D^{n-\lambda}` with its
hyperbolic descent flow, a window of levels, the attaching and belt spheres — and these
are assembled into an adapted system carrying one field and one flow across the whole
manifold. Between critical values the flow trivializes the band, so regular levels are
homeomorphic and sublevel inclusions are homotopy equivalences; across one critical value
the homological content is the exact sequence of attaching a single cell, which the
from-scratch homology supplies. On top of this sit the general-position ingredients: a
Hausdorff-dimension substitute for Sard's theorem, parametric transversality, embedded
Whitney disks in dimension at least five, and the Whitney trick itself in an explicit
polynomial bigon model.
:::

:::milestone "ms:homotopy-equivalence" (title := "A homotopy six-sphere") (paper := "§8") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:homology-theory, ms:pi1, ms:homology-x, ms:morse-theory") (members := "def:second-hurewicz-hurewicz-map, def:hurewicz-inverse, def:hurewicz-pi2-equiv, def:hurewicz-pi3-equiv, def:hurewicz-pi4-equiv, def:hurewicz-pi5-equiv, def:hurewicz-linear-equiv, def:hurewicz-pi6-equiv, thm:hurewicz-linear-equiv-natural, def:sphere-homology-equivalence-homology-equiv, thm:pi-subsingleton, thm:sphere-map-pi-six-bijective, def:finite-cells-built, def:finite-cells-relative-disk-lifting, thm:maps-lift-of-built, thm:sphere-map-relative-disk-lifting-six, thm:built-of-compact-smooth-manifold, thm:finite-homotopy-cells, thm:exists-right-homotopy-inverse, thm:sphere-homotopic-rel-of-top-class-eq, thm:homotopic-id-of-top-class, thm:right-inverse-is-left-inverse, def:sphere-homotopy-equiv, def:threefold-homotopy-equiv")
A closed simply connected manifold with the integral homology of $`S^6` is homotopy
equivalent to it, and the route taken to that is a Hurewicz ladder rather than a citation.
Degree two is done by hand — the Hurewicz map as the pushforward of the fundamental chain
of the square, a face-coherence device assembling simplex-wise homotopies into chain maps,
and a tetrahedron relation making the inverse operator kill boundaries — and degrees three
through six repeat the same argument through a generic toolbox: based simplices, a
null-homotopy engine, the staircase triangulation of the cube indexed by permutations, and
the subdivision identity it proves. Climbing the ladder against
$`H_*(X;\Z) \cong H_*(S^6;\Z)` gives $`\pi_i(X) = 0` for $`i \le 5` and
$`\pi_6(X) \cong H_6(X;\Z) \cong \Z`, so a map $`S^6 \to X` sending the fundamental class to
a generator is bijective on $`\pi_6`, both spaces being $`5`-connected. Whitehead's theorem
is replaced by an obstruction-theoretic disk-lifting property together with a finite cell
structure on $`X`, which Morse theory supplies: a compact smooth manifold is built from
finitely many cells of dimension at most its own. Lifting the identity of $`X` through that
map produces a right homotopy inverse, and a degree-one argument on the sphere — a self-map
fixing the fundamental class is homotopic to the identity — upgrades it to a two-sided one,
giving the homotopy equivalence $`X \simeq_h S^6`.
:::

:::milestone "ms:smale" (title := "Smale's recognition theorem") (paper := "§8") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:homology-theory, ms:morse-theory") (members := "def:native-morse-index, def:native-morse-count, def:native-connection-cancellation-data, thm:native-connection-cancellation-data-cancel, thm:cancel-of-transverse-level-isotopy, thm:exists-index-ordered-morse-system-preserving-critical-points, thm:remove-connections-of-index-le, thm:exists-native-morse-birth, thm:exists-one-to-three-handle-trade-of-ordered-indices, thm:exists-minimal-ordered-morse-system-without-outer-indices, def:canonical-middle-matrix, thm:cancel-from-complete-middle-family, thm:minimal-ordered-index-two-count-zero, thm:ordered-no-middle-indices-count-two, thm:exists-two-critical-point-morse-of-homotopy-six-sphere, thm:nonempty-homeomorph-of-homotopy-six-sphere, thm:local-boundary-homology-outward, def:belt-intersection-count, def:smale-tubular-bigon, thm:exists-signed-belt-cancellation-step, thm:exists-minimal-signed-belt-sphere, def:two-disk-decomposition, thm:nonempty-homeomorph-sphere-of-two-critical-points, thm:homeomorphic-six-sphere-of-homotopy-six-sphere")
Given a compact smooth six-manifold homotopy equivalent to $`S^6`, the target is a Morse
function with exactly two critical points. Rearrangement — moving critical points past one
another when no flow line connects them — puts an adapted system in index order; the birth
lemma together with a handle trade removes index $`1` at the cost of a cancelling pair in
indices $`2` and $`3`; and the first cancellation theorem, in the form that needs only a
single transverse intersection point in one regular level, cancels a pair whose belt and
attaching spheres meet once. What remains is the middle block, recorded by an integer
matrix of algebraic belt intersections between the index-$`2` and index-$`3` handles, with
the local-degree calculus turning each geometric intersection into a sign. Because the
middle homology of a homotopy sphere vanishes that matrix is surjective, and the Whitney
trick converts an algebraic unit into a geometric cancellation, so the index-$`2` count
falls to zero and, by the symmetric argument, so do the counts in indices $`4` and $`5`,
leaving one minimum and one maximum. Reeb's theorem then writes the manifold as two closed
balls glued along their boundary spheres, hence homeomorphic to $`S^6`. This is the
generalized Poincaré conjecture in dimension six, and it is where the argument leaves the
complex-analytic world for good.
:::

:::milestone "ms:main-theorem" (title := "A complex structure on the six-sphere") (paper := "Cor. 1.1") (paper_url := "https://alpo.ge/s6.pdf") (uses := "ms:threefold, ms:homotopy-equivalence, ms:smale") (members := "thm:complex-manifold-is-real-manifold, thm:space-is-real-analytic-manifold, thm:space-is-smooth-real-manifold, def:manifold-atlas-transport-charted-space, thm:manifold-atlas-transport-is-manifold, def:threefold-homeomorph, thm:exists-complex-analytic-atlas, def:unit-sphere, def:model-equiv, thm:exists-complex-atlas, thm:mathoverflow-1973")
The threefold arrives complex-analytic and Smale's theorem is a statement about real
smooth manifolds, so the first move is restriction of scalars: an atlas whose transitions
are $`n`-times continuously $`\C`-differentiable is one whose transitions are $`n`-times
continuously $`\R`-differentiable, at the same index and on the same charts, the analytic
case included. That makes $`X` a compact smooth real six-manifold, and the homotopy
equivalence with $`S^6` then yields a homeomorphism $`X \simeq_t S^6`. Transport along a
homeomorphism carries a charted space over unchanged — each chart is composed with the
inverse homeomorphism, and the transition maps of the transported atlas are literally the
transition maps of the original — so compatibility in any groupoid is inherited verbatim
and the analytic complex atlas of $`X` becomes an analytic complex atlas on the sphere.
Re-charting along the linear equivalence
$`\C \times \C^2 \cong \mathrm{EuclideanSpace}\ \C\ (\mathrm{Fin}\ 3)` puts it in the
coordinates the question is posed in, and weakening the analytic index to $`1` over the
same complex model gives the certified statement: the standard unit sphere in $`\R^7`
carries a charted-space structure on $`\C^3` making it a complex manifold. Note what is
absent. The $`h`-cobordism theorem and the vanishing of $`\Theta_6`, by which the paper
upgrades Smale's homeomorphism to a diffeomorphism, are never invoked, and no
diffeomorphism $`X \to S^6` is ever constructed; what is proved is therefore the statement
Hopf and the MathOverflow question ask for — a complex manifold whose underlying
topological space is the six-sphere — and not the stronger assertion about its standard
smooth structure.
:::

{blueprint_overview (page := false)}
